=== Myturnkeylife/Payload-tm/packages/translations/src/api/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "newAccountCreated": {
          "type": "string"
        },
        "resetYourPassword": {
          "type": "string"
        },
        "verifyYourEmail": {
          "type": "string"
        },
        "youAreReceivingResetPassword": {
          "type": "string"
        },
        "youDidNotRequestPassword": {
          "type": "string"
        }
      },
      "required": [
        "newAccountCreated",
        "resetYourPassword",
        "verifyYourEmail",
        "youAreReceivingResetPassword",
        "youDidNotRequestPassword"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "deletingFile": {
          "type": "string"
        },
        "emailOrPasswordIncorrect": {
          "type": "string"
        },
        "followingFieldsInvalid_one": {
          "type": "string"
        },
        "followingFieldsInvalid_other": {
          "type": "string"
        },
        "noFilesUploaded": {
          "type": "string"
        },
        "notAllowedToPerformAction": {
          "type": "string"
        },
        "problemUploadingFile": {
          "type": "string"
        },
        "unableToDeleteCount": {
          "type": "string"
        },
        "unableToUpdateCount": {
          "type": "string"
        },
        "unauthorized": {
          "type": "string"
        },
        "userLocked": {
          "type": "string"
        }
      },
      "required": [
        "deletingFile",
        "emailOrPasswordIncorrect",
        "followingFieldsInvalid_one",
        "followingFieldsInvalid_other",
        "noFilesUploaded",
        "notAllowedToPerformAction",
        "problemUploadingFile",
        "unableToDeleteCount",
        "unableToUpdateCount",
        "unauthorized",
        "userLocked"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addLink": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "addRelationship": {
          "type": "string"
        },
        "addUpload": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "chooseBetweenCustomTextOrDocument": {
          "type": "string"
        },
        "chooseDocumentToLink": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "chooseLabel": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "customURL": {
          "type": "string"
        },
        "editLabelData": {
          "type": "string"
        },
        "editLink": {
          "type": "string"
        },
        "editRelationship": {
          "type": "string"
        },
        "enterURL": {
          "type": "string"
        },
        "internalLink": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "labelRelationship": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "linkType": {
          "type": "string"
        },
        "linkedTo": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "newLabel": {
          "type": "string"
        },
        "openInNewTab": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "relatedDocument": {
          "type": "string"
        },
        "relationTo": {
          "type": "string"
        },
        "removeRelationship": {
          "type": "string"
        },
        "removeUpload": {
          "type": "string"
        },
        "saveChanges": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectExistingLabel": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "swapRelationship": {
          "type": "string"
        },
        "swapUpload": {
          "type": "string"
        },
        "textToDisplay": {
          "type": "string"
        },
        "toggleBlock": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "block",
        "blocks",
        "chooseBetweenCustomTextOrDocument",
        "chooseDocumentToLink",
        "customURL",
        "editLink",
        "editRelationship",
        "enterURL",
        "internalLink",
        "linkType",
        "openInNewTab",
        "textToDisplay",
        "addLabel",
        "addLink",
        "addNew",
        "addNewLabel",
        "addRelationship",
        "addUpload",
        "blockType",
        "chooseFromExisting",
        "chooseLabel",
        "collapseAll",
        "editLabelData",
        "itemsAndMore",
        "labelRelationship",
        "latitude",
        "linkedTo",
        "longitude",
        "newLabel",
        "passwordsDoNotMatch",
        "relatedDocument",
        "relationTo",
        "removeRelationship",
        "removeUpload",
        "saveChanges",
        "searchForBlock",
        "selectExistingLabel",
        "selectFieldsToEdit",
        "showAll",
        "swapRelationship",
        "swapUpload",
        "toggleBlock",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "deletedCountSuccessfully": {
          "type": "string"
        },
        "deletedSuccessfully": {
          "type": "string"
        },
        "notFound": {
          "type": "string"
        },
        "successfullyCreated": {
          "type": "string"
        },
        "updatedCountSuccessfully": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "deletedCountSuccessfully",
        "deletedSuccessfully",
        "notFound",
        "successfullyCreated",
        "updatedCountSuccessfully",
        "value"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "crop": {
          "type": "string"
        },
        "cropToolDescription": {
          "type": "string"
        },
        "dragAndDrop": {
          "type": "string"
        },
        "dragAndDropHere": {
          "type": "string"
        },
        "editImage": {
          "type": "string"
        },
        "focalPoint": {
          "type": "string"
        },
        "focalPointDescription": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "fileSize": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "lessInfo": {
          "type": "string"
        },
        "moreInfo": {
          "type": "string"
        },
        "previewSizes": {
          "type": "string"
        },
        "selectCollectionToBrowse": {
          "type": "string"
        },
        "selectFile": {
          "type": "string"
        },
        "setCropArea": {
          "type": "string"
        },
        "setFocalPoint": {
          "type": "string"
        },
        "sizes": {
          "type": "string"
        },
        "sizesFor": {
          "type": "string"
        },
        "width": {
          "type": "string"
        }
      },
      "required": [
        "dragAndDropHere",
        "fileName",
        "fileSize",
        "height",
        "lessInfo",
        "moreInfo",
        "selectCollectionToBrowse",
        "selectFile",
        "dragAndDrop",
        "sizes",
        "width"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "emailAddress": {
          "type": "string"
        },
        "enterNumber": {
          "type": "string"
        },
        "greaterThanMax": {
          "type": "string"
        },
        "invalidInput": {
          "type": "string"
        },
        "invalidSelection": {
          "type": "string"
        },
        "invalidSelections": {
          "type": "string"
        },
        "lessThanMin": {
          "type": "string"
        },
        "longerThanMin": {
          "type": "string"
        },
        "notValidDate": {
          "type": "string"
        },
        "requiresNoMoreThan": {
          "type": "string"
        },
        "requiresTwoNumbers": {
          "type": "string"
        },
        "shorterThanMax": {
          "type": "string"
        },
        "trueOrFalse": {
          "type": "string"
        },
        "validUploadID": {
          "type": "string"
        }
      },
      "required": [
        "emailAddress",
        "enterNumber",
        "greaterThanMax",
        "invalidInput",
        "invalidSelection",
        "invalidSelections",
        "lessThanMin",
        "longerThanMin",
        "notValidDate",
        "requiresNoMoreThan",
        "requiresTwoNumbers",
        "shorterThanMax",
        "trueOrFalse",
        "validUploadID"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "autosavedSuccessfully": {
          "type": "string"
        },
        "draftSavedSuccessfully": {
          "type": "string"
        },
        "restoredSuccessfully": {
          "type": "string"
        }
      },
      "required": [
        "autosavedSuccessfully",
        "draftSavedSuccessfully",
        "restoredSuccessfully"
      ],
      "type": "object"
    }
  },
  "required": [
    "general",
    "authentication",
    "error",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/bg.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "Току-що беше създаден нов профил за достъп до <a href=\"{{serverURL}}\">{{serverURL}}</a> Моля, въведи връзката в браузъра си, за да потвърдиш имейла си: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> След като потвърдиш имейла си, ще можеш да влезеш успешно.",
    "resetYourPassword": "Възстанови паролата си",
    "verifyYourEmail": "Потвърди имейла си",
    "youAreReceivingResetPassword": "Получаваш това, защото ти (или някой друг) е заявил възстановяване на паролата. Натисни връзката или постави това в браузъра си, за да довършиш процеса:",
    "youDidNotRequestPassword": "Ако не си заявил това, игнорирай този имейл и паролата ти ще остане непроменена."
  },
  "error": {
    "deletingFile": "Имаше грешка при изтриването на файла.",
    "emailOrPasswordIncorrect": "Имейлът или паролата не са правилни.",
    "followingFieldsInvalid_one": "Следното поле е некоректно:",
    "followingFieldsInvalid_other": "Следните полета са некоректни:",
    "noFilesUploaded": "Никакви файлове не бяха качени.",
    "notAllowedToPerformAction": "Нямаш право да извършиш това действие.",
    "problemUploadingFile": "Имаше проблем при качването на файла.",
    "unableToDeleteCount": "Не беше възможно да се изтрият {{count}} от {{total}} {{label}}.",
    "unableToUpdateCount": "Не беше възможно да се обновят {{count}} от {{total}} {{label}}.",
    "unauthorized": "Неавторизиран, трябва да влезеш, за да извършиш тази заявка.",
    "userLocked": "Този потребител има прекалено много невалидни опити за влизане и е заключен."
  },
  "general": {
    "deletedCountSuccessfully": "Изтрити {{count}} {{label}} успешно.",
    "deletedSuccessfully": "Изтрито успешно.",
    "notFound": "Няма открит",
    "successfullyCreated": "{{label}} успешно създаден.",
    "updatedCountSuccessfully": "Обновени {{count}} {{label}} успешно.",
    "value": "Стойност"
  },
  "validation": {
    "emailAddress": "Моля, въведи валиден имейл адрес.",
    "enterNumber": "Моля, въведи валиден номер.",
    "greaterThanMax": "{{value}} е по-голямо от максимално допустимото {{label}} от {{max}}.",
    "invalidInput": "Това поле има невалиден вход.",
    "invalidSelection": "Това поле има невалидна селекция.",
    "invalidSelections": "Това поле има следните невалидни селекции:",
    "lessThanMin": "{{value}} е по-малко от минимално допустимото {{label}} от {{min}}.",
    "longerThanMin": "Тази стойност трябва да е по-голяма от минималната стойност от {{minLength}} символа.",
    "notValidDate": "\"{{value}}\" не е валидна дата.",
    "requiresNoMoreThan": "Това поле изисква не повече от {{count}} {{label}}.",
    "requiresTwoNumbers": "Това поле изисква 2 числа.",
    "shorterThanMax": "Тази стойност трябва да е по-малка от максималната стойност от {{maxLength}} символа.",
    "trueOrFalse": "Това поле може да бъде само \"true\" или \"false\".",
    "validUploadID": "Това поле не е валиден идентификатор на качването."
  },
  "version": {
    "autosavedSuccessfully": "Успешно автоматично запазване.",
    "draftSavedSuccessfully": "Чернова запазена успешно.",
    "restoredSuccessfully": "Успешно възстановяване."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/ar.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "تمّ إنشاء حساب جديد لتتمكّن من الوصول إلى <a href=\"{{serverURL}}\"> {{serverURL}} </a> الرّجاء النّقر فوق الرّابط التّالي أو لصق عنوان URL أدناه في متصفّحّك لتأكيد بريدك الإلكتروني : <a href=\"{{verificationURL}}\"> {{verificationURL}} </a> <br> بعد التّحقّق من بريدك الإلكتروني ، ستتمكّن من تسجيل الدّخول بنجاح.",
    "resetYourPassword": "إعادة تعيين كلمة المرور الخاصّة بك",
    "verifyYourEmail": "قم بتأكيد بريدك الألكتروني",
    "youAreReceivingResetPassword": "أنت تتلقّى هذا البريد الالكتروني لأنّك (أو لأنّ شخص آخر) طلبت إعادة تعيين كلمة المرور لحسابك. الرّجاء النّقر فوق الرّابط التّالي ، أو لصق هذا الرّابط في متصفّحك لإكمال العمليّة:",
    "youDidNotRequestPassword": "إن لم تطلب هذا ، يرجى تجاهل هذا البريد الإلكتروني وستبقى كلمة مرورك ذاتها بدون تغيير."
  },
  "error": {
    "deletingFile": "حدث خطأ أثناء حذف الملف.",
    "emailOrPasswordIncorrect": "البريد الإلكتروني أو كلمة المرور المقدمة غير صحيحة.",
    "followingFieldsInvalid_one": "الحقل التالي غير صالح:",
    "followingFieldsInvalid_other": "الحقول التالية غير صالحة:",
    "noFilesUploaded": "لم يتمّ رفع أيّة ملفّات.",
    "notAllowedToPerformAction": "لا يسمح لك القيام بهذه العمليّة.",
    "problemUploadingFile": "حدث خطأ اثناء رفع الملفّ.",
    "unableToDeleteCount": "يتعذّر حذف {{count}} من {{total}} {{label}}.",
    "unableToUpdateCount": "يتعذّر تحديث {{count}} من {{total}} {{label}}.",
    "unauthorized": "غير مصرّح لك ، عليك أن تقوم بتسجيل الدّخول لتتمكّن من تقديم هذا الطّلب.",
    "userLocked": "تمّ قفل هذا المستخدم نظرًا لوجود عدد كبير من محاولات تسجيل الدّخول الغير ناجحة."
  },
  "general": {
    "deletedCountSuccessfully": "تمّ حذف {{count}} {{label}} بنجاح.",
    "deletedSuccessfully": "تمّ الحذف بنجاح.",
    "notFound": "غير موجود",
    "successfullyCreated": "{{label}} تم إنشاؤها بنجاح.",
    "updatedCountSuccessfully": "تم تحديث {{count}} {{label}} بنجاح.",
    "value": "القيمة"
  },
  "validation": {
    "emailAddress": "يرجى إدخال عنوان بريد إلكتروني صحيح.",
    "enterNumber": "يرجى إدخال رقم صحيح.",
    "greaterThanMax": "{{value}} أكبر من الحد الأقصى المسموح به {{label}} الذي يبلغ {{max}}.",
    "invalidInput": "هذا الحقل لديه إدخال غير صالح.",
    "invalidSelection": "هذا الحقل لديه اختيار غير صالح.",
    "invalidSelections": "هذا الحقل لديه الاختيارات الغير صالحة التالية:",
    "lessThanMin": "{{value}} أقل من الحد الأدنى المسموح به {{label}} الذي يبلغ {{min}}.",
    "longerThanMin": "يجب أن يكون هذا القيمة أطول من الحد الأدنى للطول الذي هو {{minLength}} أحرف.",
    "notValidDate": "\"{{value}}\" ليس تاريخا صالحا.",
    "requiresNoMoreThan": "هذا الحقل يتطلب عدم تجاوز {{count}} {{label}}.",
    "requiresTwoNumbers": "هذا الحقل يتطلب رقمين.",
    "shorterThanMax": "يجب أن تكون هذه القيمة أقصر من الحد الأقصى للطول الذي هو {{maxLength}} أحرف.",
    "trueOrFalse": "يمكن أن يكون هذا الحقل مساويًا فقط للقيمتين صحيح أو خطأ.",
    "validUploadID": "هذا الحقل ليس معرّف تحميل صالح."
  },
  "version": {
    "autosavedSuccessfully": "تمّ الحفظ التّلقائي بنجاح.",
    "draftSavedSuccessfully": "تمّ حفظ المسودّة بنجاح.",
    "restoredSuccessfully": "تمّت الاستعادة بنحاح."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/vi.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "Một tài khoản mới đã được tạo cho bạn. Tài khoản này được dùng để truy cập <a href=\"{{serverURL}}\">{{serverURL}}</a> Hãy nhấp chuột hoặc sao chép đường dẫn sau vào trình duyệt của bạn để xác thực email: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> Sau khi email được xác thực, bạn sẽ có thể đăng nhập.",
    "resetYourPassword": "Tạo lại mật khẩu",
    "verifyYourEmail": "Tiến hành xác thực email",
    "youAreReceivingResetPassword": "Bạn nhận được tin nhắn này vì bạn (hoặc một người nào khác) đã gửi yêu cầu thay đổi mật khẩu tài khoản của bạn. Xin hãy nhấp chuột vào đường dẫn sau, hoặc sao chép vào trình duyệt của bạn để hoàn tất quá trình:",
    "youDidNotRequestPassword": "Nếu bạn không phải là người yêu cầu thay đổi mật khẩu, xin hãy bỏ qua tin nhắn này và mật khẩu của bạn sẽ được giữ nguyên."
  },
  "error": {
    "deletingFile": "Lỗi - Đã xảy ra vấn đề khi xóa tệp này.",
    "emailOrPasswordIncorrect": "Lỗi - Email hoặc mật khẩu không chính xác.",
    "followingFieldsInvalid_one": "Lỗi - Field sau không hợp lệ:",
    "followingFieldsInvalid_other": "Lỗi - Những fields sau không hợp lệ:",
    "noFilesUploaded": "Lỗi - File chưa được tải lên.",
    "notAllowedToPerformAction": "Lỗi - Bạn không có quyền thực hiện lệnh này.",
    "problemUploadingFile": "Lỗi - Đã xảy ra vấn để khi tải lên file sau.",
    "unableToDeleteCount": "Không thể xóa {{count}} trong số {{total}} {{label}}.",
    "unableToUpdateCount": "Không thể cập nhật {{count}} trên {{total}} {{label}}.",
    "unauthorized": "Lỗi - Bạn cần phải đăng nhập trước khi gửi request sau.",
    "userLocked": "Lỗi- Tài khoản đã bị khóa do đăng nhập thất bại nhiều lần."
  },
  "general": {
    "deletedCountSuccessfully": "Đã xóa thành công {{count}} {{label}}.",
    "deletedSuccessfully": "Đã xoá thành công.",
    "notFound": "Không tìm thấy",
    "successfullyCreated": "{{label}} đã được tạo thành công.",
    "updatedCountSuccessfully": "Đã cập nhật thành công {{count}} {{label}}.",
    "value": "Giá trị"
  },
  "validation": {
    "emailAddress": "Địa chỉ email không hợp lệ.",
    "enterNumber": "Vui lòng nhập số.",
    "greaterThanMax": "{{value}} lớn hơn giá trị tối đa cho phép của {{label}} là {{max}}.",
    "invalidInput": "Dữ liệu nhập vào không hợp lệ.",
    "invalidSelection": "Lựa chọn ở field này không hợp lệ.",
    "invalidSelections": "'Field này có những lựa chọn không hợp lệ sau:'",
    "lessThanMin": "{{value}} nhỏ hơn giá trị tối thiểu cho phép của {{label}} là {{min}}.",
    "longerThanMin": "Giá trị này cần có độ dài tối thiểu {{minLength}} ký tự.",
    "notValidDate": "\"{{value}}\" không phải là một ngày (date) hợp lệ.",
    "requiresNoMoreThan": "Field này không thể vượt quá {{count}} {{label}}.",
    "requiresTwoNumbers": "Field này cần tối thiểu 2 chữ số.",
    "shorterThanMax": "Giá trị phải ngắn hơn hoặc bằng {{maxLength}} ký tự.",
    "trueOrFalse": "Field này chỉ có thể chứa giá trị true hoặc false.",
    "validUploadID": "'Field này không chứa ID tải lên hợp lệ.'"
  },
  "version": {
    "autosavedSuccessfully": "Đã tự động lưu thành công.",
    "draftSavedSuccessfully": "Bản nháp đã được lưu thành công.",
    "restoredSuccessfully": "Đã khôi phục thành công."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/fa.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "یک نمایه کاربری تازه برای دسترسی شما ساخته شده است <a href=\"{{serverURL}}\">{{serverURL}}</a> لطفاً روی پیوند زیر کلیک کنید یا آدرس زیر را در مرورگر خود قرار دهید تا رایانامه خود را تأیید کنید: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> پس از تایید رایانامه خود، می توانید وارد سیستم شوید.",
    "resetYourPassword": "گذرواژه خود را بازنشانی کنید",
    "verifyYourEmail": "رایانامه خود را تأیید کنید",
    "youAreReceivingResetPassword": "درخواست بازنشانی گذرواژه نمایه توسط شما یا فرد دیگری فرستاده شده است، اگر این درخواست از سمت شما بوده روی پیوند مقابل کلیک کنید یا در مرورگر وب خود پیوند را کپی کنید تا مراحل بازنشانی گذرواژه تکمیل شود، در غیر این صورت جای نگرانی نیست این پیام را نادیده بگیرید:",
    "youDidNotRequestPassword": "اگر شما این درخواست را ندادید، لطفاً این رایانامه را نادیده بگیرید و گذرواژه شما تغییری نخواهد کرد."
  },
  "error": {
    "deletingFile": "هنگام حذف فایل خطایی روی داد.",
    "emailOrPasswordIncorrect": "رایانامه یا گذرواژه ارائه شده نادرست است.",
    "followingFieldsInvalid_one": "کادر زیر نامعتبر است:",
    "followingFieldsInvalid_other": "کادرهای زیر نامعتبر هستند:",
    "noFilesUploaded": "هیچ رسانه‌ای بارگذاری نشده.",
    "notAllowedToPerformAction": "این عملیات برای شما مجاز نیست.",
    "problemUploadingFile": "هنگام بارگذاری سند خطایی رخ داد.",
    "unableToDeleteCount": "نمی‌توان {{count}} از {{total}} {{label}} را حذف کرد.",
    "unableToUpdateCount": "امکان به روز رسانی {{count}} خارج از {{total}} {{label}} وجود ندارد.",
    "unauthorized": "درخواست نامعتبر، جهت فرستادن این درخواست باید وارد شوید.",
    "userLocked": "این کاربر به دلیل تلاش های زیاد برای ورود ناموفق قفل شده است."
  },
  "general": {
    "deletedCountSuccessfully": "تعداد {{count}} {{label}} با موفقیت پاک گردید.",
    "deletedSuccessfully": "با موفقیت حذف شد.",
    "notFound": "یافت نشد",
    "successfullyCreated": "{{label}} با موفقیت ساخته شد.",
    "updatedCountSuccessfully": "تعداد {{count}} با عنوان {{label}} با موفقیت بروزرسانی شدند.",
    "value": "مقدار"
  },
  "validation": {
    "emailAddress": "لطفاً یک نشانی رایانامه معتبر وارد کنید.",
    "enterNumber": "لطفاً یک شماره درست وارد کنید.",
    "greaterThanMax": "{{value}} بیشتر از حداکثر مجاز برای {{label}} است که {{max}} است.",
    "invalidInput": "این کادر دارای ورودی نامعتبر است.",
    "invalidSelection": "این کادر دارای یک انتخاب نامعتبر است.",
    "invalidSelections": "این کادر دارای انتخاب‌های نامعتبر زیر است:",
    "lessThanMin": "{{value}} کمتر از حداقل مجاز برای {{label}} است که {{min}} است.",
    "longerThanMin": "ورودی باید بیش از حداقل {{minLength}} واژه باشد.",
    "notValidDate": "\"{{value}}\" یک تاریخ معتبر نیست.",
    "requiresNoMoreThan": "این رشته به بیش از {{count}} {{label}} نیاز دارد.",
    "requiresTwoNumbers": "این کادر به دو عدد نیاز دارد.",
    "shorterThanMax": "ورودی باید کمتر از {{maxLength}} واژه باشد.",
    "trueOrFalse": "این کادر فقط می تواند به صورت true یا false باشد.",
    "validUploadID": "این فیلد یک شناسه بارگذاری معتبر نیست."
  },
  "version": {
    "autosavedSuccessfully": "با موفقیت ذخیره خودکار شد.",
    "draftSavedSuccessfully": "پیش‌نویس با موفقیت ذخیره شد.",
    "restoredSuccessfully": "با موفقیت بازیابی شد."
  }
}
