=== Myturnkeylife/Payload-tm/packages/translations/src/api/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "newAccountCreated": {
          "type": "string"
        },
        "resetYourPassword": {
          "type": "string"
        },
        "verifyYourEmail": {
          "type": "string"
        },
        "youAreReceivingResetPassword": {
          "type": "string"
        },
        "youDidNotRequestPassword": {
          "type": "string"
        }
      },
      "required": [
        "newAccountCreated",
        "resetYourPassword",
        "verifyYourEmail",
        "youAreReceivingResetPassword",
        "youDidNotRequestPassword"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "deletingFile": {
          "type": "string"
        },
        "emailOrPasswordIncorrect": {
          "type": "string"
        },
        "followingFieldsInvalid_one": {
          "type": "string"
        },
        "followingFieldsInvalid_other": {
          "type": "string"
        },
        "noFilesUploaded": {
          "type": "string"
        },
        "notAllowedToPerformAction": {
          "type": "string"
        },
        "problemUploadingFile": {
          "type": "string"
        },
        "unableToDeleteCount": {
          "type": "string"
        },
        "unableToUpdateCount": {
          "type": "string"
        },
        "unauthorized": {
          "type": "string"
        },
        "userLocked": {
          "type": "string"
        }
      },
      "required": [
        "deletingFile",
        "emailOrPasswordIncorrect",
        "followingFieldsInvalid_one",
        "followingFieldsInvalid_other",
        "noFilesUploaded",
        "notAllowedToPerformAction",
        "problemUploadingFile",
        "unableToDeleteCount",
        "unableToUpdateCount",
        "unauthorized",
        "userLocked"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addLink": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "addRelationship": {
          "type": "string"
        },
        "addUpload": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "chooseBetweenCustomTextOrDocument": {
          "type": "string"
        },
        "chooseDocumentToLink": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "chooseLabel": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "customURL": {
          "type": "string"
        },
        "editLabelData": {
          "type": "string"
        },
        "editLink": {
          "type": "string"
        },
        "editRelationship": {
          "type": "string"
        },
        "enterURL": {
          "type": "string"
        },
        "internalLink": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "labelRelationship": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "linkType": {
          "type": "string"
        },
        "linkedTo": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "newLabel": {
          "type": "string"
        },
        "openInNewTab": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "relatedDocument": {
          "type": "string"
        },
        "relationTo": {
          "type": "string"
        },
        "removeRelationship": {
          "type": "string"
        },
        "removeUpload": {
          "type": "string"
        },
        "saveChanges": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectExistingLabel": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "swapRelationship": {
          "type": "string"
        },
        "swapUpload": {
          "type": "string"
        },
        "textToDisplay": {
          "type": "string"
        },
        "toggleBlock": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "block",
        "blocks",
        "chooseBetweenCustomTextOrDocument",
        "chooseDocumentToLink",
        "customURL",
        "editLink",
        "editRelationship",
        "enterURL",
        "internalLink",
        "linkType",
        "openInNewTab",
        "textToDisplay",
        "addLabel",
        "addLink",
        "addNew",
        "addNewLabel",
        "addRelationship",
        "addUpload",
        "blockType",
        "chooseFromExisting",
        "chooseLabel",
        "collapseAll",
        "editLabelData",
        "itemsAndMore",
        "labelRelationship",
        "latitude",
        "linkedTo",
        "longitude",
        "newLabel",
        "passwordsDoNotMatch",
        "relatedDocument",
        "relationTo",
        "removeRelationship",
        "removeUpload",
        "saveChanges",
        "searchForBlock",
        "selectExistingLabel",
        "selectFieldsToEdit",
        "showAll",
        "swapRelationship",
        "swapUpload",
        "toggleBlock",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "deletedCountSuccessfully": {
          "type": "string"
        },
        "deletedSuccessfully": {
          "type": "string"
        },
        "notFound": {
          "type": "string"
        },
        "successfullyCreated": {
          "type": "string"
        },
        "updatedCountSuccessfully": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "deletedCountSuccessfully",
        "deletedSuccessfully",
        "notFound",
        "successfullyCreated",
        "updatedCountSuccessfully",
        "value"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "crop": {
          "type": "string"
        },
        "cropToolDescription": {
          "type": "string"
        },
        "dragAndDrop": {
          "type": "string"
        },
        "dragAndDropHere": {
          "type": "string"
        },
        "editImage": {
          "type": "string"
        },
        "focalPoint": {
          "type": "string"
        },
        "focalPointDescription": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "fileSize": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "lessInfo": {
          "type": "string"
        },
        "moreInfo": {
          "type": "string"
        },
        "previewSizes": {
          "type": "string"
        },
        "selectCollectionToBrowse": {
          "type": "string"
        },
        "selectFile": {
          "type": "string"
        },
        "setCropArea": {
          "type": "string"
        },
        "setFocalPoint": {
          "type": "string"
        },
        "sizes": {
          "type": "string"
        },
        "sizesFor": {
          "type": "string"
        },
        "width": {
          "type": "string"
        }
      },
      "required": [
        "dragAndDropHere",
        "fileName",
        "fileSize",
        "height",
        "lessInfo",
        "moreInfo",
        "selectCollectionToBrowse",
        "selectFile",
        "dragAndDrop",
        "sizes",
        "width"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "emailAddress": {
          "type": "string"
        },
        "enterNumber": {
          "type": "string"
        },
        "greaterThanMax": {
          "type": "string"
        },
        "invalidInput": {
          "type": "string"
        },
        "invalidSelection": {
          "type": "string"
        },
        "invalidSelections": {
          "type": "string"
        },
        "lessThanMin": {
          "type": "string"
        },
        "longerThanMin": {
          "type": "string"
        },
        "notValidDate": {
          "type": "string"
        },
        "requiresNoMoreThan": {
          "type": "string"
        },
        "requiresTwoNumbers": {
          "type": "string"
        },
        "shorterThanMax": {
          "type": "string"
        },
        "trueOrFalse": {
          "type": "string"
        },
        "validUploadID": {
          "type": "string"
        }
      },
      "required": [
        "emailAddress",
        "enterNumber",
        "greaterThanMax",
        "invalidInput",
        "invalidSelection",
        "invalidSelections",
        "lessThanMin",
        "longerThanMin",
        "notValidDate",
        "requiresNoMoreThan",
        "requiresTwoNumbers",
        "shorterThanMax",
        "trueOrFalse",
        "validUploadID"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "autosavedSuccessfully": {
          "type": "string"
        },
        "draftSavedSuccessfully": {
          "type": "string"
        },
        "restoredSuccessfully": {
          "type": "string"
        }
      },
      "required": [
        "autosavedSuccessfully",
        "draftSavedSuccessfully",
        "restoredSuccessfully"
      ],
      "type": "object"
    }
  },
  "required": [
    "general",
    "authentication",
    "error",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/sv.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "Ett nytt konto har precis skapats som du kan komma åt <a href=\"{{serverURL}}\">{{serverURL}}</a> Klicka på följande länk eller klistra in webbadressen nedan i din webbläsare för att verifiera din e-post: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> Efter att ha verifierat din e-post kommer du att kunna logga in framgångsrikt.",
    "resetYourPassword": "Återställ Ditt Lösenord",
    "verifyYourEmail": "Verifiera din epost",
    "youAreReceivingResetPassword": "Du får detta för att du (eller någon annan) har begärt återställning av lösenordet för ditt konto. Klicka på följande länk eller klistra in den i din webbläsare för att slutföra processen:",
    "youDidNotRequestPassword": "Om du inte begärde detta, ignorera detta e-postmeddelande och ditt lösenord kommer att förbli oförändrat."
  },
  "error": {
    "deletingFile": "Det gick inte att ta bort filen.",
    "emailOrPasswordIncorrect": "E-postadressen eller lösenordet som angivits är felaktigt.",
    "followingFieldsInvalid_one": "Följande fält är ogiltigt:",
    "followingFieldsInvalid_other": "Följande fält är ogiltiga:",
    "noFilesUploaded": "Inga filer laddades upp.",
    "notAllowedToPerformAction": "Du får inte utföra denna åtgärd.",
    "problemUploadingFile": "Det uppstod ett problem när filen laddades upp.",
    "unableToDeleteCount": "Det gick inte att ta bort {{count}} av {{total}} {{label}}.",
    "unableToUpdateCount": "Det gick inte att uppdatera {{count}} av {{total}} {{label}}.",
    "unauthorized": "Obehörig, du måste vara inloggad för att göra denna begäran.",
    "userLocked": "Den här användaren är låst på grund av för många misslyckade inloggningsförsök."
  },
  "general": {
    "deletedCountSuccessfully": "Raderade {{count}} {{label}} framgångsrikt.",
    "deletedSuccessfully": "Togs bort framgångsrikt.",
    "notFound": "Hittades inte",
    "successfullyCreated": "{{label}} skapades framgångsrikt.",
    "updatedCountSuccessfully": "Uppdaterade {{count}} {{label}} framgångsrikt.",
    "value": "Värde"
  },
  "validation": {
    "emailAddress": "Vänligen ange en giltig e-postadress.",
    "enterNumber": "Vänligen skriv in ett giltigt nummer.",
    "greaterThanMax": "{{value}} är större än den maximalt tillåtna {{label}} av {{max}}.",
    "invalidInput": "Det här fältet har en ogiltig inmatning.",
    "invalidSelection": "Det här fältet har ett ogiltigt urval.",
    "invalidSelections": "Det här fältet har följande ogiltiga val:",
    "lessThanMin": "{{value}} är mindre än den minst tillåtna {{label}} av {{min}}.",
    "longerThanMin": "Detta värde måste vara längre än minimilängden på {{minLength}} tecken.",
    "notValidDate": "\"{{value}}\" är inte ett giltigt datum.",
    "requiresNoMoreThan": "Detta fält kräver inte mer än {{count}} {{label}}.",
    "requiresTwoNumbers": "Detta fält kräver två nummer.",
    "shorterThanMax": "Detta värde måste vara kortare än maxlängden på {{maxLength}} tecken.",
    "trueOrFalse": "Detta fält kan bara vara lika med sant eller falskt.",
    "validUploadID": "Det här fältet är inte ett giltigt uppladdnings-ID"
  },
  "version": {
    "autosavedSuccessfully": "Autosparades framgångsrikt.",
    "draftSavedSuccessfully": "Utkastet sparades framgångsrikt.",
    "restoredSuccessfully": "Återställd framgångsrikt."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/cs.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "Pro přístup k <a href=\"{{serverURL}}\">{{serverURL}}</a> byl pro vás vytvořen nový účet. Klepněte na následující odkaz nebo zkopírujte URL do svého prohlížeče pro ověření vašeho emailu: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> Po ověření vašeho emailu se budete moci úspěšně přihlásit.",
    "resetYourPassword": "Resetujte své heslo",
    "verifyYourEmail": "Ověřte svůj email",
    "youAreReceivingResetPassword": "Tento email obdržíte, protože jste (nebo někdo jiný) požádali o resetování hesla pro váš účet.",
    "youDidNotRequestPassword": "Pokud jste o to nepožádali, ignorujte prosím tento e-mail a vaše heslo zůstane nezměněno."
  },
  "error": {
    "deletingFile": "Při mazání souboru došlo k chybě.",
    "emailOrPasswordIncorrect": "Zadaný email nebo heslo není správné.",
    "followingFieldsInvalid_one": "Následující pole je neplatné:",
    "followingFieldsInvalid_other": "Následující pole jsou neplatná:",
    "noFilesUploaded": "Nebyly nahrány žádné soubory.",
    "notAllowedToPerformAction": "Nemáte povolení provádět tuto akci.",
    "problemUploadingFile": "Při nahrávání souboru došlo k chybě.",
    "unableToDeleteCount": "Nelze smazat {{count}} z {{total}} {{label}}",
    "unableToUpdateCount": "Nelze aktualizovat {{count}} z {{total}} {{label}}.",
    "unauthorized": "Neautorizováno, pro zadání tohoto požadavku musíte být přihlášeni.",
    "userLocked": "Tento uživatel je uzamčen kvůli příliš mnoha neúspěšným pokusům o přihlášení."
  },
  "general": {
    "deletedCountSuccessfully": "Úspěšně smazáno {{count}} {{label}}.",
    "deletedSuccessfully": "Úspěšně odstraněno.",
    "notFound": "Nenalezeno",
    "successfullyCreated": "{{label}} úspěšně vytvořeno.",
    "updatedCountSuccessfully": "Úspěšně aktualizováno {{count}} {{label}}.",
    "value": "Hodnota"
  },
  "validation": {
    "emailAddress": "Zadejte prosím platnou e-mailovou adresu.",
    "enterNumber": "Zadejte prosím platné číslo.",
    "greaterThanMax": "{{value}} je vyšší než maximálně povolená {{label}} {{max}}.",
    "invalidInput": "Toto pole má neplatný vstup.",
    "invalidSelection": "Toto pole má neplatný výběr.",
    "invalidSelections": "Toto pole má následující neplatné výběry:",
    "lessThanMin": "{{value}} je nižší než minimálně povolená {{label}} {{min}}.",
    "longerThanMin": "Tato hodnota musí být delší než minimální délka {{minLength}} znaků.",
    "notValidDate": "\"{{value}}\" není platné datum.",
    "requiresNoMoreThan": "Toto pole vyžaduje ne více než {{count}} {{label}}.",
    "requiresTwoNumbers": "Toto pole vyžaduje dvě čísla.",
    "shorterThanMax": "Tato hodnota musí být kratší než maximální délka {{maxLength}} znaků.",
    "trueOrFalse": "Toto pole může být rovno pouze true nebo false.",
    "validUploadID": "Toto pole není platné ID pro odeslání."
  },
  "version": {
    "autosavedSuccessfully": "Úspěšně uloženo automaticky.",
    "draftSavedSuccessfully": "Koncept úspěšně uložen.",
    "restoredSuccessfully": "Úspěšně obnoveno."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/it.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "Un nuovo account è appena stato creato per te per accedere a <a href=\"{{serverURL}}\">{{serverURL}}</a> Clicca sul seguente link o incolla l'URL qui sotto nel browser per verificare la tua email: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> Dopo aver verificato la tua email, sarai in grado di effettuare il log in con successo.",
    "resetYourPassword": "Modifica la tua Password",
    "verifyYourEmail": "Verifica la tua email",
    "youAreReceivingResetPassword": "Ricevi questo messaggio perché tu (o qualcun altro) hai richiesto la modifica della password per il tuo account. Clicca sul seguente link o incollalo nel browser per completare il processo:",
    "youDidNotRequestPassword": "Se non l'hai richiesto, ignora questa email e la tua password rimarrà invariata."
  },
  "error": {
    "deletingFile": "Si è verificato un errore durante l'eleminazione del file.",
    "emailOrPasswordIncorrect": "L'email o la password fornita non è corretta.",
    "followingFieldsInvalid_one": "Il seguente campo non è valido:",
    "followingFieldsInvalid_other": "I seguenti campi non sono validi:",
    "noFilesUploaded": "Nessun file è stato caricato.",
    "notAllowedToPerformAction": "Non sei autorizzato a eseguire questa azione.",
    "problemUploadingFile": "Si è verificato un problema durante il caricamento del file.",
    "unableToDeleteCount": "Impossibile eliminare {{count}} su {{total}} {{label}}.",
    "unableToUpdateCount": "Impossibile aggiornare {{count}} su {{total}} {{label}}.",
    "unauthorized": "Non autorizzato, devi essere loggato per effettuare questa richiesta.",
    "userLocked": "Questo utente è bloccato a causa di troppi tentativi di accesso non riusciti."
  },
  "general": {
    "deletedCountSuccessfully": "{{count}} {{label}} eliminato con successo.",
    "deletedSuccessfully": "Eliminato con successo.",
    "notFound": "Non Trovato",
    "successfullyCreated": "{{label}} creato con successo.",
    "updatedCountSuccessfully": "{{count}} {{label}} aggiornato con successo.",
    "value": "Valore"
  },
  "validation": {
    "emailAddress": "Si prega di inserire un indirizzo email valido.",
    "enterNumber": "Si prega di inserire un numero valido.",
    "greaterThanMax": "{{value}} è superiore al massimo consentito {{label}} di {{max}}.",
    "invalidInput": "Questo campo ha un input non valido.",
    "invalidSelection": "Questo campo ha una selezione non valida.",
    "invalidSelections": "'In questo campo sono presenti le seguenti selezioni non valide:'",
    "lessThanMin": "{{value}} è inferiore al minimo consentito {{label}} di {{min}}.",
    "longerThanMin": "Questo valore deve essere più lungo della lunghezza minima di {{minLength}} caratteri.",
    "notValidDate": "\"{{value}}\" non è una data valida.",
    "requiresNoMoreThan": "Questo campo richiede non più di {{count}} {{label}}.",
    "requiresTwoNumbers": "Questo campo richiede due numeri.",
    "shorterThanMax": "Questo valore deve essere inferiore alla lunghezza massima di {{maxLength}} caratteri.",
    "trueOrFalse": "Questo campo può essere solo uguale a 'true' o 'false'.",
    "validUploadID": "'Questo campo non è un ID di Upload valido.'"
  },
  "version": {
    "autosavedSuccessfully": "Salvataggio automatico riuscito.",
    "draftSavedSuccessfully": "Bozza salvata con successo.",
    "restoredSuccessfully": "Ripristinato con successo."
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/zh-tw.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "剛剛為您建立了一個可以存取 <a href=\"{{serverURL}}\">{{serverURL}}</a> 的新帳戶。請點擊以下連結或在瀏覽器中貼上以下網址以驗證您的電子郵件：<a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> 驗證您的電子郵件後，您將能夠成功登入。",
    "resetYourPassword": "重設您的密碼",
    "verifyYourEmail": "驗證您的電子郵件",
    "youAreReceivingResetPassword": "您收到此郵件是因為您（或其他人）已請求重設您帳戶的密碼。請點擊以下連結，或將其貼上到您的瀏覽器中以完成該過程：",
    "youDidNotRequestPassword": "如果您沒有要求這樣做，請忽略這封郵件，您的密碼將保持不變。"
  },
  "error": {
    "deletingFile": "刪除文件時出現了錯誤。",
    "emailOrPasswordIncorrect": "提供的電子郵件或密碼不正確。",
    "followingFieldsInvalid_one": "下面的字串是無效的：",
    "followingFieldsInvalid_other": "以下字串是無效的：",
    "noFilesUploaded": "沒有上傳文件。",
    "notAllowedToPerformAction": "您不被允許執行此操作。",
    "problemUploadingFile": "上傳文件時出現了問題。",
    "unableToDeleteCount": "無法從 {{total}} 個中刪除 {{count}} 個 {{label}}。",
    "unableToUpdateCount": "無法從 {{total}} 個中更新 {{count}} 個 {{label}}。",
    "unauthorized": "未經授權，您必須登錄才能提出這個請求。",
    "userLocked": "該使用者由於有太多次失敗的登錄嘗試而被鎖定。"
  },
  "general": {
    "deletedCountSuccessfully": "已成功刪除 {{count}} 個 {{label}}。",
    "deletedSuccessfully": "已成功刪除。",
    "notFound": "未找到",
    "successfullyCreated": "成功建立{{label}}",
    "updatedCountSuccessfully": "已成功更新 {{count}} 個 {{label}}。",
    "value": "值"
  },
  "validation": {
    "emailAddress": "請輸入一個有效的電子郵件地址。",
    "enterNumber": "請輸入一個有效的數字。",
    "greaterThanMax": "{{value}}超過了允許的最大{{label}}，該最大值為{{max}}。",
    "invalidInput": "這個字串有一個無效的輸入。",
    "invalidSelection": "這個字串有一個無效的選擇。",
    "invalidSelections": "這個字串有以下無效的選擇：",
    "lessThanMin": "{{value}}小於允許的最小{{label}}，該最小值為{{min}}。",
    "longerThanMin": "該值必須大於{{minLength}}字串的最小長度",
    "notValidDate": "\"{{value}}\"不是一個有效的日期。",
    "requiresNoMoreThan": "該字串要求不超過 {{count}} 個 {{label}。",
    "requiresTwoNumbers": "該字串需要兩個數字。",
    "shorterThanMax": "該值長度必須小於{{maxLength}}個字元",
    "trueOrFalse": "該字串只能等於是或否。",
    "validUploadID": "該字串不是有效的上傳ID。"
  },
  "version": {
    "autosavedSuccessfully": "自動儲存成功。",
    "draftSavedSuccessfully": "草稿儲存成功。",
    "restoredSuccessfully": "回復成功。"
  }
}

=== Myturnkeylife/Payload-tm/packages/translations/src/api/my.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "newAccountCreated": "<a href=\"{{serverURL}}\">{{serverURL}}</a> သို့ဝင်ရောက်ရန် သင့်အီးမေးလ်ကို အတည်ပြုရန်အတွက် အကောင့်အသစ်တစ်ခုကို ယခုလေးတင် ဖန်တီးပြီးပါပြီ။ ကျေးဇူးပြု၍ အောက်ပါလင့်ခ်ကို နှိပ်ပါ သို့မဟုတ် သင့်အီးမေးလ်ကို အတည်ပြုရန် ဖော်ပြပါ လင့်ခ်ကို သင့်ဘရောက်ဆာထဲသို့ ကူးထည့်ပါ- <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> သင့်အီးမေးလ်ကို အတည်ပြုပြီးနောက်၊ သင်သည် အောင်မြင်စွာ လော့ဂ်အင်ဝင်နိုင်ပါမည်။",
    "resetYourPassword": "သင့်စကားဝှက်ကို ပြန်လည်သတ်မှတ်ပါ။",
    "verifyYourEmail": "သင့်အီးမေးလ်ကို အတည်ပြုပါ။",
    "youAreReceivingResetPassword": "သင့်အကောင့်အတွက် စကားဝှက်ကို ပြန်လည်သတ်မှတ်ရန် သင် (သို့မဟုတ် အခြားသူတစ်ဦးဦး) က တောင်းဆိုထားသောကြောင့်လက်ခံရရှိခြင်းဖြစ်သည်။ ကျေးဇူးပြု၍ အောက်ပါလင့်ခ်ကို နှိပ်ပါ (သို့မဟုတ်) ၎င်းကို သင့်ဘရောက်ဆာထဲသို့ ကူးထည့်ပါ။",
    "youDidNotRequestPassword": "ယခု လုပ်ဆောင်ချက်ကို သင်မတောင်းဆိုထားပါက ဤအီးမေးလ်ကို လျစ်လျူရှုထားခြင်းဖြင့် သင့်စကားဝှက်သည် ပြောင်းလဲမည်မဟုတ်ပါ။"
  },
  "error": {
    "deletingFile": "ဖိုင်ကိုဖျက်ရာတွင် အမှားအယွင်းရှိနေသည်။",
    "emailOrPasswordIncorrect": "ထည့်သွင်းထားသော အီးမေးလ် သို့မဟုတ် စကားဝှက်သည် မမှန်ပါ။",
    "followingFieldsInvalid_one": "ထည့်သွင်းထားသော အချက်အလက်သည် မမှန်ကန်ပါ။",
    "followingFieldsInvalid_other": "ထည့်သွင်းထားသော အချက်အလက်များသည် မမှန်ကန်ပါ။",
    "noFilesUploaded": "ဖိုင်များကို အပ်လုဒ်လုပ်ထားခြင်းမရှိပါ။",
    "notAllowedToPerformAction": "ဤလုပ်ဆောင်ချက်ကို လုပ်ဆောင်ရန် ခွင့်မပြုပါ။",
    "problemUploadingFile": "ဖိုင်ကို အပ်လုဒ်တင်ရာတွင် ပြဿနာရှိနေသည်။",
    "unableToDeleteCount": "{{total}} {{label}} မှ {{count}} ကို ဖျက်၍မရပါ။",
    "unableToUpdateCount": "{{total}} {{label}} မှ {{count}} ကို အပ်ဒိတ်လုပ်၍မရပါ။",
    "unauthorized": "အခွင့်မရှိပါ။ ဤတောင်းဆိုချက်ကို လုပ်ဆောင်နိုင်ရန် သင်သည် လော့ဂ်အင်ဝင်ရပါမည်။",
    "userLocked": "အကောင့်ထဲကို ဝင်ရန် အရမ်းအရမ်းကို ကြိုးပမ်းနေသောကြောင့် အကောင့်အား လော့ခ်ချလိုက်ပါသည်။"
  },
  "general": {
    "deletedCountSuccessfully": "{{count}} {{label}} ကို အောင်မြင်စွာ ဖျက်လိုက်ပါပြီ။",
    "deletedSuccessfully": "အောင်မြင်စွာ ဖျက်လိုက်ပါပြီ။",
    "notFound": "ဘာမှ မရှိတော့ဘူး။",
    "successfullyCreated": "{{label}} အောင်မြင်စွာဖန်တီးခဲ့သည်။",
    "updatedCountSuccessfully": "{{count}} {{label}} ကို အောင်မြင်စွာ အပ်ဒိတ်လုပ်ခဲ့သည်။",
    "value": "တန်ဖိုး"
  },
  "validation": {
    "emailAddress": "မှန်ကန်သော အီးမေးလ်လိပ်စာကို ထည့်သွင်းပါ။",
    "enterNumber": "မှန်ကန်သောနံပါတ်တစ်ခုထည့်ပါ။",
    "greaterThanMax": "{{value}} သည် {{max}} ထက် ပိုမိုကြီးသည်။ ဤသည်ဖြင့် {{label}} အများဆုံးခွင့်ပြုထားသော တန်ဖိုးထက် ကြီးသည်။",
    "invalidInput": "ဤအကွက်တွင် မမှန်ကန်သော ထည့်သွင်းမှုတစ်ခုရှိသည်။",
    "invalidSelection": "ဤအကွက်တွင် မမှန်ကန်သော ရွေးချယ်မှုတစ်ခုရှိသည်။",
    "invalidSelections": "ဤအကွက်တွင် အောက်ပါ မမှန်ကန်သော ရွေးချယ်မှုများ ရှိသည်",
    "lessThanMin": "{{value}} သည် {{min}} ထက် ပိုမိုနိမ့်သည်။ ဤသည်ဖြင့် {{label}} အနည်းဆုံးခွင့်ပြုထားသော တန်ဖိုးထက် နိမ့်သည်။",
    "longerThanMin": "ဤတန်ဖိုးသည် အနိမ့်ဆုံးအရှည် {{minLength}} စာလုံးထက် ပိုရှည်ရမည်။",
    "notValidDate": "\"{{value}}\" သည် တရားဝင်ရက်စွဲမဟုတ်ပါ။",
    "requiresNoMoreThan": "ဤအကွက်တွင် {{count}} {{label}} ထက် မပိုရပါ။",
    "requiresTwoNumbers": "ဤအကွက်သည် နံပါတ်နှစ်ခု လိုအပ်ပါသည်။",
    "shorterThanMax": "ဤတန်ဖိုးသည် စာလုံး {{maxLength}} လုံး၏ အမြင့်ဆုံးအရှည်ထက် ပိုတိုရပါမည်။",
    "trueOrFalse": "ဤအကွက်သည် တစ်ခုခုဖြစ်ရပါမည်။",
    "validUploadID": "'ဤအကွက်သည် မှန်ကန်သော အပ်လုဒ် ID မဟုတ်ပါ။'"
  },
  "version": {
    "autosavedSuccessfully": "အလိုအလျောက် သိမ်းဆည်းပြီးပါပြီ။",
    "draftSavedSuccessfully": "မူကြမ်းကို အောင်မြင်စွာ သိမ်းဆည်းပြီးပါပြီ။",
    "restoredSuccessfully": "အောင်မြင်စွာ ပြန်လည်ရယူခဲ့သည်။"
  }
}
