=== Myturnkeylife/Payload-tm/packages/next/src/translations/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "account": {
          "type": "string"
        },
        "accountOfCurrentUser": {
          "type": "string"
        },
        "alreadyActivated": {
          "type": "string"
        },
        "alreadyLoggedIn": {
          "type": "string"
        },
        "backToLogin": {
          "type": "string"
        },
        "beginCreateFirstUser": {
          "type": "string"
        },
        "changePassword": {
          "type": "string"
        },
        "confirmGeneration": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        },
        "emailNotValid": {
          "type": "string"
        },
        "emailSent": {
          "type": "string"
        },
        "enableAPIKey": {
          "type": "string"
        },
        "failedToUnlock": {
          "type": "string"
        },
        "forceUnlock": {
          "type": "string"
        },
        "forgotPassword": {
          "type": "string"
        },
        "forgotPasswordEmailInstructions": {
          "type": "string"
        },
        "forgotPasswordQuestion": {
          "type": "string"
        },
        "generate": {
          "type": "string"
        },
        "generateNewAPIKey": {
          "type": "string"
        },
        "logBackIn": {
          "type": "string"
        },
        "loggedOutInactivity": {
          "type": "string"
        },
        "login": {
          "type": "string"
        },
        "logOut": {
          "type": "string"
        },
        "logout": {
          "type": "string"
        },
        "logoutUser": {
          "type": "string"
        },
        "newAPIKeyGenerated": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "resetPassword": {
          "type": "string"
        },
        "stayLoggedIn": {
          "type": "string"
        },
        "successfullyUnlocked": {
          "type": "string"
        },
        "unableToVerify": {
          "type": "string"
        },
        "verified": {
          "type": "string"
        },
        "verifiedSuccessfully": {
          "type": "string"
        },
        "verify": {
          "type": "string"
        },
        "verifyUser": {
          "type": "string"
        },
        "youAreInactive": {
          "type": "string"
        }
      },
      "required": [
        "account",
        "accountOfCurrentUser",
        "alreadyActivated",
        "alreadyLoggedIn",
        "backToLogin",
        "beginCreateFirstUser",
        "changePassword",
        "confirmGeneration",
        "confirmPassword",
        "emailNotValid",
        "emailSent",
        "enableAPIKey",
        "failedToUnlock",
        "forceUnlock",
        "forgotPassword",
        "forgotPasswordEmailInstructions",
        "forgotPasswordQuestion",
        "generate",
        "generateNewAPIKey",
        "logBackIn",
        "loggedOutInactivity",
        "login",
        "logOut",
        "logout",
        "logoutUser",
        "newAPIKeyGenerated",
        "newPassword",
        "resetPassword",
        "stayLoggedIn",
        "successfullyUnlocked",
        "unableToVerify",
        "verified",
        "verifiedSuccessfully",
        "verify",
        "verifyUser",
        "youAreInactive"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "autosaving": {
          "type": "string"
        },
        "correctInvalidFields": {
          "type": "string"
        },
        "deletingTitle": {
          "type": "string"
        },
        "loadingDocument": {
          "type": "string"
        },
        "noMatchedField": {
          "type": "string"
        },
        "notAllowedToAccessPage": {
          "type": "string"
        },
        "previewing": {
          "type": "string"
        },
        "unknown": {
          "type": "string"
        }
      },
      "required": [
        "autosaving",
        "correctInvalidFields",
        "deletingTitle",
        "loadingDocument",
        "noMatchedField",
        "notAllowedToAccessPage",
        "previewing",
        "unknown"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "addLabel",
        "addNew",
        "addNewLabel",
        "block",
        "blocks",
        "blockType",
        "chooseFromExisting",
        "collapseAll",
        "itemsAndMore",
        "latitude",
        "longitude",
        "passwordsDoNotMatch",
        "searchForBlock",
        "selectFieldsToEdit",
        "showAll",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "addBelow": {
          "type": "string"
        },
        "addFilter": {
          "type": "string"
        },
        "adminTheme": {
          "type": "string"
        },
        "and": {
          "type": "string"
        },
        "applyChanges": {
          "type": "string"
        },
        "ascending": {
          "type": "string"
        },
        "automatic": {
          "type": "string"
        },
        "backToDashboard": {
          "type": "string"
        },
        "cancel": {
          "type": "string"
        },
        "changesNotSaved": {
          "type": "string"
        },
        "close": {
          "type": "string"
        },
        "collapse": {
          "type": "string"
        },
        "collections": {
          "type": "string"
        },
        "columns": {
          "type": "string"
        },
        "columnToSort": {
          "type": "string"
        },
        "confirm": {
          "type": "string"
        },
        "confirmDeletion": {
          "type": "string"
        },
        "confirmDuplication": {
          "type": "string"
        },
        "copied": {
          "type": "string"
        },
        "copy": {
          "type": "string"
        },
        "create": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "createNew": {
          "type": "string"
        },
        "createNewLabel": {
          "type": "string"
        },
        "creating": {
          "type": "string"
        },
        "creatingNewLabel": {
          "type": "string"
        },
        "dark": {
          "type": "string"
        },
        "dashboard": {
          "type": "string"
        },
        "delete": {
          "type": "string"
        },
        "deleting": {
          "type": "string"
        },
        "descending": {
          "type": "string"
        },
        "deselectAllRows": {
          "type": "string"
        },
        "duplicate": {
          "type": "string"
        },
        "duplicateWithoutSaving": {
          "type": "string"
        },
        "edit": {
          "type": "string"
        },
        "editing": {
          "type": "string"
        },
        "editLabel": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "emailAddress": {
          "type": "string"
        },
        "enterAValue": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "errors": {
          "type": "string"
        },
        "fallbackToDefaultLocale": {
          "type": "string"
        },
        "filters": {
          "type": "string"
        },
        "filterWhere": {
          "type": "string"
        },
        "globals": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "lastModified": {
          "type": "string"
        },
        "leaveAnyway": {
          "type": "string"
        },
        "leaveWithoutSaving": {
          "type": "string"
        },
        "light": {
          "type": "string"
        },
        "livePreview": {
          "type": "string"
        },
        "loading": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "menu": {
          "type": "string"
        },
        "moveDown": {
          "type": "string"
        },
        "moveUp": {
          "type": "string"
        },
        "noFiltersSet": {
          "type": "string"
        },
        "noLabel": {
          "type": "string"
        },
        "none": {
          "type": "string"
        },
        "noOptions": {
          "type": "string"
        },
        "noResults": {
          "type": "string"
        },
        "nothingFound": {
          "type": "string"
        },
        "noValue": {
          "type": "string"
        },
        "of": {
          "type": "string"
        },
        "open": {
          "type": "string"
        },
        "or": {
          "type": "string"
        },
        "order": {
          "type": "string"
        },
        "pageNotFound": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "payloadSettings": {
          "type": "string"
        },
        "perPage": {
          "type": "string"
        },
        "remove": {
          "type": "string"
        },
        "reset": {
          "type": "string"
        },
        "save": {
          "type": "string"
        },
        "searchBy": {
          "type": "string"
        },
        "selectAll": {
          "type": "string"
        },
        "selectAllRows": {
          "type": "string"
        },
        "selectedCount": {
          "type": "string"
        },
        "selectValue": {
          "type": "string"
        },
        "showAllLabel": {
          "type": "string"
        },
        "sorryNotFound": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "sortByLabelDirection": {
          "type": "string"
        },
        "stayOnThisPage": {
          "type": "string"
        },
        "submissionSuccessful": {
          "type": "string"
        },
        "submit": {
          "type": "string"
        },
        "successfullyDuplicated": {
          "type": "string"
        },
        "titleDeleted": {
          "type": "string"
        },
        "untitled": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "updating": {
          "type": "string"
        },
        "welcome": {
          "type": "string"
        }
      },
      "required": [
        "addBelow",
        "addFilter",
        "adminTheme",
        "and",
        "ascending",
        "automatic",
        "backToDashboard",
        "cancel",
        "changesNotSaved",
        "close",
        "collections",
        "columns",
        "columnToSort",
        "confirm",
        "confirmDeletion",
        "confirmDuplication",
        "copied",
        "copy",
        "create",
        "created",
        "createNew",
        "createNewLabel",
        "creating",
        "creatingNewLabel",
        "dark",
        "dashboard",
        "delete",
        "deleting",
        "descending",
        "duplicate",
        "duplicateWithoutSaving",
        "edit",
        "editing",
        "editLabel",
        "email",
        "emailAddress",
        "enterAValue",
        "error",
        "errors",
        "fallbackToDefaultLocale",
        "filters",
        "filterWhere",
        "globals",
        "language",
        "lastModified",
        "leaveAnyway",
        "leaveWithoutSaving",
        "light",
        "loading",
        "moveDown",
        "moveUp",
        "noFiltersSet",
        "noLabel",
        "none",
        "noResults",
        "nothingFound",
        "noValue",
        "of",
        "or",
        "order",
        "pageNotFound",
        "password",
        "payloadSettings",
        "perPage",
        "remove",
        "save",
        "searchBy",
        "selectAll",
        "selectedCount",
        "selectValue",
        "sorryNotFound",
        "sort",
        "stayOnThisPage",
        "submissionSuccessful",
        "submit",
        "successfullyDuplicated",
        "titleDeleted",
        "untitled",
        "updatedAt",
        "updating",
        "welcome"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "crop": {
          "type": "string"
        },
        "cropToolDescription": {
          "type": "string"
        },
        "dragAndDrop": {
          "type": "string"
        },
        "editImage": {
          "type": "string"
        },
        "focalPoint": {
          "type": "string"
        },
        "focalPointDescription": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "previewSizes": {
          "type": "string"
        },
        "selectCollectionToBrowse": {
          "type": "string"
        },
        "selectFile": {
          "type": "string"
        },
        "setCropArea": {
          "type": "string"
        },
        "setFocalPoint": {
          "type": "string"
        },
        "sizesFor": {
          "type": "string"
        },
        "width": {
          "type": "string"
        }
      },
      "required": [
        "dragAndDrop",
        "height",
        "selectCollectionToBrowse",
        "selectFile",
        "width"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "fieldHasNo": {
          "type": "string"
        },
        "limitReached": {
          "type": "string"
        }
      },
      "required": [
        "fieldHasNo"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "aboutToRestore": {
          "type": "string"
        },
        "aboutToRestoreGlobal": {
          "type": "string"
        },
        "compareVersion": {
          "type": "string"
        },
        "confirmUnpublish": {
          "type": "string"
        },
        "confirmVersionRestoration": {
          "type": "string"
        },
        "noFurtherVersionsFound": {
          "type": "string"
        },
        "noRowsFound": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "problemRestoringVersion": {
          "type": "string"
        },
        "publishChanges": {
          "type": "string"
        },
        "restoreThisVersion": {
          "type": "string"
        },
        "restoring": {
          "type": "string"
        },
        "selectLocales": {
          "type": "string"
        },
        "selectVersionToCompare": {
          "type": "string"
        },
        "showLocales": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "unpublish": {
          "type": "string"
        },
        "unpublishing": {
          "type": "string"
        },
        "versionCreatedOn": {
          "type": "string"
        },
        "versionID": {
          "type": "string"
        },
        "versions": {
          "type": "string"
        },
        "viewingVersion": {
          "type": "string"
        },
        "viewingVersionGlobal": {
          "type": "string"
        },
        "viewingVersions": {
          "type": "string"
        },
        "viewingVersionsGlobal": {
          "type": "string"
        }
      },
      "required": [
        "aboutToRestore",
        "aboutToRestoreGlobal",
        "compareVersion",
        "confirmUnpublish",
        "confirmVersionRestoration",
        "noFurtherVersionsFound",
        "noRowsFound",
        "preview",
        "problemRestoringVersion",
        "publishChanges",
        "restoreThisVersion",
        "restoring",
        "selectLocales",
        "selectVersionToCompare",
        "showLocales",
        "type",
        "unpublish",
        "unpublishing",
        "versionCreatedOn",
        "versionID",
        "versions",
        "viewingVersion",
        "viewingVersionGlobal",
        "viewingVersions",
        "viewingVersionsGlobal"
      ],
      "type": "object"
    }
  },
  "required": [
    "authentication",
    "error",
    "fields",
    "general",
    "upload",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/next/src/translations/rs-latin.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "account": "Nalog",
    "accountOfCurrentUser": "Nalog trenutnog korisnika",
    "alreadyActivated": "Već aktivirano",
    "alreadyLoggedIn": "Već prijavljen",
    "backToLogin": "Nazad na prijavu",
    "beginCreateFirstUser": "Na samom početku kreiraj svog prvog korisnika",
    "changePassword": "Promeni lozinku",
    "confirmGeneration": "Potvrdi kreiranje",
    "confirmPassword": "Potvrdi lozinku",
    "emailNotValid": "Adresa e-pošte nije validna",
    "emailSent": "Poruka e-pošte prosleđena",
    "enableAPIKey": "Omogući API ključ",
    "failedToUnlock": "Neuspešno otključavanje.",
    "forceUnlock": "Prinudno otključaj",
    "forgotPassword": "Zaboravljena lozinka",
    "forgotPasswordEmailInstructions": "Molimo Vas da unesete svoj adresu e-pošte. Primićete poruku sa uputstvom za ponovno postavljanje lozinke.",
    "forgotPasswordQuestion": "Zaboravljena lozinka?",
    "generate": "Generiši",
    "generateNewAPIKey": "Generiši novi API ključ",
    "logBackIn": "Ponovna prijava",
    "logOut": "Odjava",
    "loggedOutInactivity": "Odjavljeni se zbog neaktivnosti.",
    "login": "Prijava",
    "logout": "Odjava",
    "logoutUser": "Odjava korisnika",
    "newAPIKeyGenerated": "Novi API ključ generisan.",
    "newPassword": "Nova lozinka",
    "resetPassword": "Promena lozinke",
    "stayLoggedIn": "Ostani prijavljen",
    "successfullyUnlocked": "Uspešno otključano",
    "unableToVerify": "Nije moguće potvrditi",
    "verified": "Potvrđeno",
    "verifiedSuccessfully": "Uspešno potvrđeno",
    "verify": "Potvrdi",
    "verifyUser": "Potvrdi korisnika",
    "youAreInactive": "Neaktivni ste već neko vreme i uskoro ćete biti automatski odjavljeni zbog sigurnosti. Da li želite ostati prijavljeni?"
  },
  "error": {
    "autosaving": "Nastao je problem pri automatskom čuvanju ovog dokumenta.",
    "correctInvalidFields": "Molimo ispravite nevalidna polja.",
    "deletingTitle": "Dogodila se greška pri brisanju {{title}}. Proverite internet konekciju i pokušajte ponovo.",
    "loadingDocument": "Postoji problem pri učitavanju dokumenta čiji je ID {{id}}.",
    "noMatchedField": "Nema podudarajućih polja za \"{{label}}\"",
    "notAllowedToAccessPage": "Nemate dozvolu za pristup ovoj stranici.",
    "previewing": "Postoji problem pri pregledu ovog dokumenta.",
    "unknown": "Došlo je do nepoznate greške."
  },
  "fields": {
    "addLabel": "Dodaj {{label}}",
    "addNew": "Dodaj novi",
    "addNewLabel": "Dodaj novi {{label}}",
    "block": "blokiranje",
    "blockType": "Vrsta blokiranja",
    "blocks": "blokiranja",
    "chooseFromExisting": "Odaberite iz postojećih.",
    "collapseAll": "Skupi sve",
    "itemsAndMore": "{{items}} i {{count}} više",
    "latitude": "Geografska širina",
    "longitude": "Geografska dužina",
    "passwordsDoNotMatch": "Lozinke nisu iste.",
    "searchForBlock": "Pretraži blok",
    "selectFieldsToEdit": "Odaberite polja za promenu",
    "showAll": "Pokaži sve",
    "uploadNewLabel": "Učitaj novi {{label}}"
  },
  "general": {
    "addBelow": "Dodaj ispod",
    "addFilter": "Dodaj filter",
    "adminTheme": "Administratorska tema",
    "and": "I",
    "applyChanges": "Primeni promene",
    "ascending": "Uzlazno",
    "automatic": "Automatsko",
    "backToDashboard": "Nazad na kontrolni panel",
    "cancel": "Otkaži",
    "changesNotSaved": "Vaše promene nisu sačuvane. Ako izađete sada, izgubićete promene.",
    "close": "Zatvori",
    "collapse": "Skupi",
    "collections": "Kolekcije",
    "columnToSort": "Kolona za sortiranje",
    "columns": "Kolone",
    "confirm": "Potvrdi",
    "confirmDeletion": "Potvrdi brisanje",
    "confirmDuplication": "Potvrdi duplikaciju",
    "copied": "Kopirano",
    "copy": "Kopiraj",
    "create": "Kreiraj",
    "createNew": "Kreiraj novo",
    "createNewLabel": "Kreiraj novo {{label}}",
    "created": "Kreirano",
    "creating": "Kreira se",
    "creatingNewLabel": "Kreiranje novog {{label}}",
    "dark": "Tamno",
    "dashboard": "Kontrolni panel",
    "delete": "Obriši",
    "deleting": "Brisanje...",
    "descending": "Opadajuće",
    "deselectAllRows": "Deselektujte sve redove",
    "duplicate": "Duplikat",
    "duplicateWithoutSaving": "Ponovi bez čuvanja promena",
    "edit": "Uredi",
    "editLabel": "Uredi {{label}}",
    "editing": "Uređivanje",
    "email": "E-pošta",
    "emailAddress": "Аdresa e-pošte",
    "enterAValue": "Unesi vrednost",
    "error": "Greška",
    "errors": "Greške",
    "fallbackToDefaultLocale": "Vraćanje na zadati jezik",
    "filterWhere": "Filter {{label}} gde",
    "filters": "Filteri",
    "globals": "Globali",
    "language": "Jezik",
    "lastModified": "Zadnja promena",
    "leaveAnyway": "Svejedno napusti",
    "leaveWithoutSaving": "Napusti bez čuvanja",
    "light": "Svetlo",
    "livePreview": "Pregled",
    "loading": "Učitavanje",
    "locale": "Jezik",
    "menu": "Meni",
    "moveDown": "Pomeri dole",
    "moveUp": "Pomeri gore",
    "noFiltersSet": "Nema postavljenih filtera",
    "noLabel": "<Nema {{label}}>",
    "noOptions": "Nema opcija",
    "noResults": "Nema pronađenih {{label}}. Moguće da {{label}} još uvek ne postoji ili nema rezultata u skladu sa postavljenim filterima.",
    "noValue": "Bez vrednosti",
    "none": "Nijedan",
    "nothingFound": "Ništa nije pronađeno",
    "of": "Od",
    "open": "Otvori",
    "or": "Ili",
    "order": "Redosled",
    "pageNotFound": "Stranica nije pronađena",
    "password": "Lozinka",
    "payloadSettings": "Payload postavke",
    "perPage": "Po stranici: {{limit}}",
    "remove": "Ukloni",
    "reset": "Ponovo postavi",
    "save": "Sačuvaj",
    "searchBy": "Traži po {{label}}",
    "selectAll": "Odaberite sve {{count}} {{label}}",
    "selectAllRows": "Odaberite sve redove",
    "selectValue": "Odaberi vrednost",
    "selectedCount": "{{count}} {{label}} odabrano",
    "showAllLabel": "Prikaži sve {{label}}",
    "sorryNotFound": "Nažalost, ne postoji ništa što odgovara vašem zahtevu.",
    "sort": "Sortiraj",
    "sortByLabelDirection": "Sortiraj prema {{label}} {{direction}}",
    "stayOnThisPage": "Ostani na ovoj stranici",
    "submissionSuccessful": "Uspešno slanje",
    "submit": "Potvrdi",
    "successfullyDuplicated": "{{label}} uspešno duplicirano.",
    "titleDeleted": "{{label}} \"{{title}}\" uspešno obrisano.",
    "untitled": "Bez naslova",
    "updatedAt": "Ažurirano u",
    "updating": "Ažuriranje",
    "welcome": "Dobrodošli"
  },
  "upload": {
    "crop": "Isecite sliku",
    "cropToolDescription": "Prevucite uglove izabranog područja, nacrtajte novo područje ili prilagodite vrednosti ispod.",
    "dragAndDrop": "Prevucite i ispustite datoteku",
    "editImage": "Uredi sliku",
    "focalPoint": "Centralna tačka",
    "focalPointDescription": "Prevucite središnju tačku direktno na pregled ili prilagodite vrednosti ispod.",
    "height": "Visina",
    "previewSizes": "Veličine pregleda",
    "selectCollectionToBrowse": "Odaberite kolekciju za pregled",
    "selectFile": "Odaberite datoteku",
    "setCropArea": "Postavite područje za isečenu sliku",
    "setFocalPoint": "Postavite centralnu tačku",
    "sizesFor": "Veličine za {{label}}",
    "width": "Širina"
  },
  "validation": {
    "fieldHasNo": "Ovo polje nema {{label}}",
    "limitReached": "Dosegnut je limit, može se dodati samo {{max}} stavki."
  },
  "version": {
    "aboutToRestore": "Vratićete {{label}} dokument u stanje u kojem je bio {{versionDate}}",
    "aboutToRestoreGlobal": "Vratićete globalni {{label}} u stanje u kojem je bio {{versionDate}}.",
    "compareVersion": "Uporedi verziju sa:",
    "confirmUnpublish": "Potvrdite poništavanje objave",
    "confirmVersionRestoration": "Potvrdite vraćanje verzije",
    "noFurtherVersionsFound": "Nisu pronađene naredne verzije",
    "noRowsFound": "{{label}} nije pronađeno",
    "preview": "Pregled",
    "problemRestoringVersion": "Nastao je problem pri vraćanju ove verzije",
    "publishChanges": "Objavi promene",
    "restoreThisVersion": "Vrati ovu verziju",
    "restoring": "Vraćanje...",
    "selectLocales": "Odaberite jezike",
    "selectVersionToCompare": "Odaberite verziju za upoređivanje",
    "showLocales": "Prikaži jezike:",
    "type": "Tip",
    "unpublish": "Poništi objavu",
    "unpublishing": "Poništavanje objave...",
    "versionCreatedOn": "{{version}} kreiranih:",
    "versionID": "ID verzije",
    "versions": "Verzije",
    "viewingVersion": "Pregled verzije za {{entityLabel}} {{documentTitle}}",
    "viewingVersionGlobal": "Pregled verzije za globalni {{entityLabel}}",
    "viewingVersions": "Pregled verzija za {{entityLabel}} {{documentTitle}}",
    "viewingVersionsGlobal": "Pregled verzije za globalni {{entityLabel}}"
  }
}
