=== Myturnkeylife/Payload-tm/packages/next/src/translations/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "account": {
          "type": "string"
        },
        "accountOfCurrentUser": {
          "type": "string"
        },
        "alreadyActivated": {
          "type": "string"
        },
        "alreadyLoggedIn": {
          "type": "string"
        },
        "backToLogin": {
          "type": "string"
        },
        "beginCreateFirstUser": {
          "type": "string"
        },
        "changePassword": {
          "type": "string"
        },
        "confirmGeneration": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        },
        "emailNotValid": {
          "type": "string"
        },
        "emailSent": {
          "type": "string"
        },
        "enableAPIKey": {
          "type": "string"
        },
        "failedToUnlock": {
          "type": "string"
        },
        "forceUnlock": {
          "type": "string"
        },
        "forgotPassword": {
          "type": "string"
        },
        "forgotPasswordEmailInstructions": {
          "type": "string"
        },
        "forgotPasswordQuestion": {
          "type": "string"
        },
        "generate": {
          "type": "string"
        },
        "generateNewAPIKey": {
          "type": "string"
        },
        "logBackIn": {
          "type": "string"
        },
        "loggedOutInactivity": {
          "type": "string"
        },
        "login": {
          "type": "string"
        },
        "logOut": {
          "type": "string"
        },
        "logout": {
          "type": "string"
        },
        "logoutUser": {
          "type": "string"
        },
        "newAPIKeyGenerated": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "resetPassword": {
          "type": "string"
        },
        "stayLoggedIn": {
          "type": "string"
        },
        "successfullyUnlocked": {
          "type": "string"
        },
        "unableToVerify": {
          "type": "string"
        },
        "verified": {
          "type": "string"
        },
        "verifiedSuccessfully": {
          "type": "string"
        },
        "verify": {
          "type": "string"
        },
        "verifyUser": {
          "type": "string"
        },
        "youAreInactive": {
          "type": "string"
        }
      },
      "required": [
        "account",
        "accountOfCurrentUser",
        "alreadyActivated",
        "alreadyLoggedIn",
        "backToLogin",
        "beginCreateFirstUser",
        "changePassword",
        "confirmGeneration",
        "confirmPassword",
        "emailNotValid",
        "emailSent",
        "enableAPIKey",
        "failedToUnlock",
        "forceUnlock",
        "forgotPassword",
        "forgotPasswordEmailInstructions",
        "forgotPasswordQuestion",
        "generate",
        "generateNewAPIKey",
        "logBackIn",
        "loggedOutInactivity",
        "login",
        "logOut",
        "logout",
        "logoutUser",
        "newAPIKeyGenerated",
        "newPassword",
        "resetPassword",
        "stayLoggedIn",
        "successfullyUnlocked",
        "unableToVerify",
        "verified",
        "verifiedSuccessfully",
        "verify",
        "verifyUser",
        "youAreInactive"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "autosaving": {
          "type": "string"
        },
        "correctInvalidFields": {
          "type": "string"
        },
        "deletingTitle": {
          "type": "string"
        },
        "loadingDocument": {
          "type": "string"
        },
        "noMatchedField": {
          "type": "string"
        },
        "notAllowedToAccessPage": {
          "type": "string"
        },
        "previewing": {
          "type": "string"
        },
        "unknown": {
          "type": "string"
        }
      },
      "required": [
        "autosaving",
        "correctInvalidFields",
        "deletingTitle",
        "loadingDocument",
        "noMatchedField",
        "notAllowedToAccessPage",
        "previewing",
        "unknown"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "addLabel",
        "addNew",
        "addNewLabel",
        "block",
        "blocks",
        "blockType",
        "chooseFromExisting",
        "collapseAll",
        "itemsAndMore",
        "latitude",
        "longitude",
        "passwordsDoNotMatch",
        "searchForBlock",
        "selectFieldsToEdit",
        "showAll",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "addBelow": {
          "type": "string"
        },
        "addFilter": {
          "type": "string"
        },
        "adminTheme": {
          "type": "string"
        },
        "and": {
          "type": "string"
        },
        "applyChanges": {
          "type": "string"
        },
        "ascending": {
          "type": "string"
        },
        "automatic": {
          "type": "string"
        },
        "backToDashboard": {
          "type": "string"
        },
        "cancel": {
          "type": "string"
        },
        "changesNotSaved": {
          "type": "string"
        },
        "close": {
          "type": "string"
        },
        "collapse": {
          "type": "string"
        },
        "collections": {
          "type": "string"
        },
        "columns": {
          "type": "string"
        },
        "columnToSort": {
          "type": "string"
        },
        "confirm": {
          "type": "string"
        },
        "confirmDeletion": {
          "type": "string"
        },
        "confirmDuplication": {
          "type": "string"
        },
        "copied": {
          "type": "string"
        },
        "copy": {
          "type": "string"
        },
        "create": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "createNew": {
          "type": "string"
        },
        "createNewLabel": {
          "type": "string"
        },
        "creating": {
          "type": "string"
        },
        "creatingNewLabel": {
          "type": "string"
        },
        "dark": {
          "type": "string"
        },
        "dashboard": {
          "type": "string"
        },
        "delete": {
          "type": "string"
        },
        "deleting": {
          "type": "string"
        },
        "descending": {
          "type": "string"
        },
        "deselectAllRows": {
          "type": "string"
        },
        "duplicate": {
          "type": "string"
        },
        "duplicateWithoutSaving": {
          "type": "string"
        },
        "edit": {
          "type": "string"
        },
        "editing": {
          "type": "string"
        },
        "editLabel": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "emailAddress": {
          "type": "string"
        },
        "enterAValue": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "errors": {
          "type": "string"
        },
        "fallbackToDefaultLocale": {
          "type": "string"
        },
        "filters": {
          "type": "string"
        },
        "filterWhere": {
          "type": "string"
        },
        "globals": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "lastModified": {
          "type": "string"
        },
        "leaveAnyway": {
          "type": "string"
        },
        "leaveWithoutSaving": {
          "type": "string"
        },
        "light": {
          "type": "string"
        },
        "livePreview": {
          "type": "string"
        },
        "loading": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "menu": {
          "type": "string"
        },
        "moveDown": {
          "type": "string"
        },
        "moveUp": {
          "type": "string"
        },
        "noFiltersSet": {
          "type": "string"
        },
        "noLabel": {
          "type": "string"
        },
        "none": {
          "type": "string"
        },
        "noOptions": {
          "type": "string"
        },
        "noResults": {
          "type": "string"
        },
        "nothingFound": {
          "type": "string"
        },
        "noValue": {
          "type": "string"
        },
        "of": {
          "type": "string"
        },
        "open": {
          "type": "string"
        },
        "or": {
          "type": "string"
        },
        "order": {
          "type": "string"
        },
        "pageNotFound": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "payloadSettings": {
          "type": "string"
        },
        "perPage": {
          "type": "string"
        },
        "remove": {
          "type": "string"
        },
        "reset": {
          "type": "string"
        },
        "save": {
          "type": "string"
        },
        "searchBy": {
          "type": "string"
        },
        "selectAll": {
          "type": "string"
        },
        "selectAllRows": {
          "type": "string"
        },
        "selectedCount": {
          "type": "string"
        },
        "selectValue": {
          "type": "string"
        },
        "showAllLabel": {
          "type": "string"
        },
        "sorryNotFound": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "sortByLabelDirection": {
          "type": "string"
        },
        "stayOnThisPage": {
          "type": "string"
        },
        "submissionSuccessful": {
          "type": "string"
        },
        "submit": {
          "type": "string"
        },
        "successfullyDuplicated": {
          "type": "string"
        },
        "titleDeleted": {
          "type": "string"
        },
        "untitled": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "updating": {
          "type": "string"
        },
        "welcome": {
          "type": "string"
        }
      },
      "required": [
        "addBelow",
        "addFilter",
        "adminTheme",
        "and",
        "ascending",
        "automatic",
        "backToDashboard",
        "cancel",
        "changesNotSaved",
        "close",
        "collections",
        "columns",
        "columnToSort",
        "confirm",
        "confirmDeletion",
        "confirmDuplication",
        "copied",
        "copy",
        "create",
        "created",
        "createNew",
        "createNewLabel",
        "creating",
        "creatingNewLabel",
        "dark",
        "dashboard",
        "delete",
        "deleting",
        "descending",
        "duplicate",
        "duplicateWithoutSaving",
        "edit",
        "editing",
        "editLabel",
        "email",
        "emailAddress",
        "enterAValue",
        "error",
        "errors",
        "fallbackToDefaultLocale",
        "filters",
        "filterWhere",
        "globals",
        "language",
        "lastModified",
        "leaveAnyway",
        "leaveWithoutSaving",
        "light",
        "loading",
        "moveDown",
        "moveUp",
        "noFiltersSet",
        "noLabel",
        "none",
        "noResults",
        "nothingFound",
        "noValue",
        "of",
        "or",
        "order",
        "pageNotFound",
        "password",
        "payloadSettings",
        "perPage",
        "remove",
        "save",
        "searchBy",
        "selectAll",
        "selectedCount",
        "selectValue",
        "sorryNotFound",
        "sort",
        "stayOnThisPage",
        "submissionSuccessful",
        "submit",
        "successfullyDuplicated",
        "titleDeleted",
        "untitled",
        "updatedAt",
        "updating",
        "welcome"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "crop": {
          "type": "string"
        },
        "cropToolDescription": {
          "type": "string"
        },
        "dragAndDrop": {
          "type": "string"
        },
        "editImage": {
          "type": "string"
        },
        "focalPoint": {
          "type": "string"
        },
        "focalPointDescription": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "previewSizes": {
          "type": "string"
        },
        "selectCollectionToBrowse": {
          "type": "string"
        },
        "selectFile": {
          "type": "string"
        },
        "setCropArea": {
          "type": "string"
        },
        "setFocalPoint": {
          "type": "string"
        },
        "sizesFor": {
          "type": "string"
        },
        "width": {
          "type": "string"
        }
      },
      "required": [
        "dragAndDrop",
        "height",
        "selectCollectionToBrowse",
        "selectFile",
        "width"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "fieldHasNo": {
          "type": "string"
        },
        "limitReached": {
          "type": "string"
        }
      },
      "required": [
        "fieldHasNo"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "aboutToRestore": {
          "type": "string"
        },
        "aboutToRestoreGlobal": {
          "type": "string"
        },
        "compareVersion": {
          "type": "string"
        },
        "confirmUnpublish": {
          "type": "string"
        },
        "confirmVersionRestoration": {
          "type": "string"
        },
        "noFurtherVersionsFound": {
          "type": "string"
        },
        "noRowsFound": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "problemRestoringVersion": {
          "type": "string"
        },
        "publishChanges": {
          "type": "string"
        },
        "restoreThisVersion": {
          "type": "string"
        },
        "restoring": {
          "type": "string"
        },
        "selectLocales": {
          "type": "string"
        },
        "selectVersionToCompare": {
          "type": "string"
        },
        "showLocales": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "unpublish": {
          "type": "string"
        },
        "unpublishing": {
          "type": "string"
        },
        "versionCreatedOn": {
          "type": "string"
        },
        "versionID": {
          "type": "string"
        },
        "versions": {
          "type": "string"
        },
        "viewingVersion": {
          "type": "string"
        },
        "viewingVersionGlobal": {
          "type": "string"
        },
        "viewingVersions": {
          "type": "string"
        },
        "viewingVersionsGlobal": {
          "type": "string"
        }
      },
      "required": [
        "aboutToRestore",
        "aboutToRestoreGlobal",
        "compareVersion",
        "confirmUnpublish",
        "confirmVersionRestoration",
        "noFurtherVersionsFound",
        "noRowsFound",
        "preview",
        "problemRestoringVersion",
        "publishChanges",
        "restoreThisVersion",
        "restoring",
        "selectLocales",
        "selectVersionToCompare",
        "showLocales",
        "type",
        "unpublish",
        "unpublishing",
        "versionCreatedOn",
        "versionID",
        "versions",
        "viewingVersion",
        "viewingVersionGlobal",
        "viewingVersions",
        "viewingVersionsGlobal"
      ],
      "type": "object"
    }
  },
  "required": [
    "authentication",
    "error",
    "fields",
    "general",
    "upload",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/next/src/translations/it.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "account": "Account",
    "accountOfCurrentUser": "Account dell'utente corrente",
    "alreadyActivated": "Già Attivato",
    "alreadyLoggedIn": "Sei già loggato",
    "backToLogin": "Torna al login",
    "beginCreateFirstUser": "Per iniziare, crea il tuo primo utente.",
    "changePassword": "Cambia Password",
    "confirmGeneration": "Conferma Generazione",
    "confirmPassword": "Conferma Password",
    "emailNotValid": "L'email fornita non è valida",
    "emailSent": "Email Inviata",
    "enableAPIKey": "Abilita la Chiave API",
    "failedToUnlock": "Lo sblocco è fallito",
    "forceUnlock": "Forza Sblocco",
    "forgotPassword": "Cambia Password",
    "forgotPasswordEmailInstructions": "Inserisci la tua mail qui sotto. Riceverai un messaggio email con le istruzioni su come cambiare la tua password.",
    "forgotPasswordQuestion": "Password dimenticata?",
    "generate": "Genera",
    "generateNewAPIKey": "Genera una nuova Chiave API",
    "logBackIn": "Vai al Log in",
    "logOut": "Log out",
    "loggedOutInactivity": "Sei stato disconnesso automaticamente per inattività.",
    "login": "Login",
    "logout": "Logout",
    "logoutUser": "Logout utente",
    "newAPIKeyGenerated": "Nuova Chiave API Generata.",
    "newPassword": "Nuova Password",
    "resetPassword": "Modifica Password",
    "stayLoggedIn": "Rimani connesso",
    "successfullyUnlocked": "Sbloccato con successo",
    "unableToVerify": "Impossibile verificare",
    "verified": "Verificato",
    "verifiedSuccessfully": "Verificato con successo",
    "verify": "Verifica",
    "verifyUser": "Verifica Utente",
    "youAreInactive": "Non sei attivo da un po' di tempo e a breve verrai disconnesso automaticamente per la tua sicurezza. Vuoi rimanere connesso?"
  },
  "error": {
    "autosaving": "Si è verificato un problema durante il salvataggio automatico di questo documento.",
    "correctInvalidFields": "Per favore correggi i campi non validi.",
    "deletingTitle": "Si è verificato un errore durante l'eliminazione di {{title}}. Per favore controlla la tua connessione e riprova.",
    "loadingDocument": "Si è verificato un problema durante il caricamento del documento con ID {{id}}.",
    "noMatchedField": "Nessun campo corrispondente trovato per \"{{label}}\"",
    "notAllowedToAccessPage": "Non sei autorizzato ad accedere a questa pagina.",
    "previewing": "Si è verificato un problema durante l'anteprima di questo documento.",
    "unknown": "Si è verificato un errore sconosciuto."
  },
  "fields": {
    "addLabel": "Aggiungi {{label}}",
    "addNew": "Aggiungi nuovo",
    "addNewLabel": "Aggiungi nuovo {{label}}",
    "block": "blocco",
    "blockType": "Tipo di Blocco",
    "blocks": "blocchi",
    "chooseFromExisting": "Scegli tra esistente",
    "collapseAll": "Comprimi tutto",
    "itemsAndMore": "{{items}} e altri {{count}}",
    "latitude": "Latitudine",
    "longitude": "Longitudine",
    "passwordsDoNotMatch": "Le password non corrispondono.",
    "searchForBlock": "Cerca un blocco",
    "selectFieldsToEdit": "Seleziona i campi da modificare",
    "showAll": "Mostra tutto",
    "uploadNewLabel": "Carica nuovo {{label}}"
  },
  "general": {
    "addBelow": "Aggiungi sotto",
    "addFilter": "Aggiungi Filtro",
    "adminTheme": "Tema Admin",
    "and": "E",
    "applyChanges": "Applica modifiche",
    "ascending": "Ascendente",
    "automatic": "Automatico",
    "backToDashboard": "Torna alla Dashboard",
    "cancel": "Cancella",
    "changesNotSaved": "Le tue modifiche non sono state salvate. Se esci ora, verranno perse.",
    "close": "Chiudere",
    "collapse": "Comprimi",
    "collections": "Collezioni",
    "columnToSort": "Colonna da Ordinare",
    "columns": "Colonne",
    "confirm": "Conferma",
    "confirmDeletion": "Conferma l'eliminazione",
    "confirmDuplication": "Conferma la duplicazione",
    "copied": "Copiato",
    "copy": "Copia",
    "create": "Crea",
    "createNew": "Crea Nuovo",
    "createNewLabel": "Crea nuovo {{label}}",
    "created": "Data di creazione",
    "creating": "Crea nuovo",
    "creatingNewLabel": "Creazione di un nuovo {{label}}",
    "dark": "Scuro",
    "dashboard": "Dashboard",
    "delete": "Elimina",
    "deleting": "Sto eliminando...",
    "descending": "Decrescente",
    "deselectAllRows": "Deseleziona tutte le righe",
    "duplicate": "Duplica",
    "duplicateWithoutSaving": "Duplica senza salvare le modifiche",
    "edit": "Modificare",
    "editLabel": "Modifica {{label}}",
    "editing": "Modifica",
    "email": "Email",
    "emailAddress": "Indirizzo Email",
    "enterAValue": "Inserisci un valore",
    "error": "Errore",
    "errors": "Errori",
    "fallbackToDefaultLocale": "Fallback al locale predefinito",
    "filterWhere": "Filtra {{label}} se",
    "filters": "Filtri",
    "globals": "Globali",
    "language": "Lingua",
    "lastModified": "Ultima modifica",
    "leaveAnyway": "Esci comunque",
    "leaveWithoutSaving": "Esci senza salvare",
    "light": "Chiaro",
    "livePreview": "Anteprima dal vivo",
    "loading": "Caricamento",
    "locale": "Locale",
    "menu": "Menù",
    "moveDown": "Sposta sotto",
    "moveUp": "Sposta sopra",
    "noFiltersSet": "Nessun filtro impostato",
    "noLabel": "<No {{label}}>",
    "noOptions": "Nessuna opzione",
    "noResults": "Nessun {{label}} trovato. Non esiste ancora nessun {{label}} oppure nessuno corrisponde ai filtri che hai specificato sopra.",
    "noValue": "Nessun valore",
    "none": "Nessuno",
    "nothingFound": "Non è stato trovato nulla",
    "of": "di",
    "open": "Apri",
    "or": "Oppure",
    "order": "Ordine",
    "pageNotFound": "Pagina non trovata",
    "password": "Password",
    "payloadSettings": "Impostazioni di Payload",
    "perPage": "Per Pagina: {{limit}}",
    "remove": "Rimuovi",
    "reset": "Ripristina",
    "save": "Salva",
    "searchBy": "Cerca per {{label}}",
    "selectAll": "Seleziona tutto {{count}} {{label}}",
    "selectAllRows": "Seleziona tutte le righe",
    "selectValue": "Seleziona un valore",
    "selectedCount": "{{count}} {{label}} selezionato",
    "showAllLabel": "Mostra tutti {{label}}",
    "sorryNotFound": "Siamo spiacenti, non c'è nulla che corrisponda alla tua richiesta.",
    "sort": "Ordina",
    "sortByLabelDirection": "Ordina per {{label}} {{direction}}",
    "stayOnThisPage": "Rimani su questa pagina",
    "submissionSuccessful": "Invio riuscito.",
    "submit": "Invia",
    "successfullyDuplicated": "{{label}} duplicato con successo.",
    "titleDeleted": "{{label}} {{title}} eliminato con successo.",
    "untitled": "Senza titolo",
    "updatedAt": "Aggiornato il",
    "updating": "Aggiornamento",
    "welcome": "Benvenuto"
  },
  "upload": {
    "crop": "Raccolto",
    "cropToolDescription": "Trascina gli angoli dell'area selezionata, disegna una nuova area o regola i valori qui sotto.",
    "dragAndDrop": "Trascina e rilascia un file",
    "editImage": "Modifica immagine",
    "focalPoint": "Punto Focale",
    "focalPointDescription": "Trascina il punto focale direttamente sull'anteprima o regola i valori sottostanti.",
    "height": "Altezza",
    "previewSizes": "Anteprime Dimensioni",
    "selectCollectionToBrowse": "Seleziona una Collezione da Sfogliare",
    "selectFile": "Seleziona un file",
    "setCropArea": "Imposta area di ritaglio",
    "setFocalPoint": "Imposta punto focale",
    "sizesFor": "Dimensioni per {{label}}",
    "width": "Larghezza"
  },
  "validation": {
    "fieldHasNo": "Questo campo non ha {{label}}",
    "limitReached": "Raggiunto il limite, possono essere aggiunti solo {{max}} elementi."
  },
  "version": {
    "aboutToRestore": "Stai per ripristinare questo documento {{label}} allo stato in cui si trovava il {{versionDate}}.",
    "aboutToRestoreGlobal": "Stai per ripristinare {{label}} allo stato in cui si trovava il {{versionDate}}.",
    "compareVersion": "Confronta versione con:",
    "confirmUnpublish": "Conferma annullamento della pubblicazione",
    "confirmVersionRestoration": "Conferma il ripristino della versione",
    "noFurtherVersionsFound": "Non sono state trovate ulteriori versioni",
    "noRowsFound": "Nessun {{label}} trovato",
    "preview": "Anteprima",
    "problemRestoringVersion": "Si è verificato un problema durante il ripristino di questa versione",
    "publishChanges": "Pubblica modifiche",
    "restoreThisVersion": "Ripristina questa versione",
    "restoring": "Ripristino...",
    "selectLocales": "Seleziona le lingue da visualizzare",
    "selectVersionToCompare": "Seleziona una versione da confrontare",
    "showLocales": "Mostra localizzazioni:",
    "type": "Tipo",
    "unpublish": "Annulla pubblicazione",
    "unpublishing": "Annullamento pubblicazione...",
    "versionCreatedOn": "{{version}} creata il:",
    "versionID": "ID Versione",
    "versions": "Versioni",
    "viewingVersion": "Visualizzazione della versione per {{entityLabel}} {{documentTitle}}",
    "viewingVersionGlobal": "`Visualizzazione della versione per {{entityLabel}}",
    "viewingVersions": "Visualizzazione delle versioni per {{entityLabel}} {{documentTitle}}",
    "viewingVersionsGlobal": "`Visualizzazione delle versioni per {{entityLabel}}"
  }
}
