=== Myturnkeylife/Payload-tm/packages/next/src/translations/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "account": {
          "type": "string"
        },
        "accountOfCurrentUser": {
          "type": "string"
        },
        "alreadyActivated": {
          "type": "string"
        },
        "alreadyLoggedIn": {
          "type": "string"
        },
        "backToLogin": {
          "type": "string"
        },
        "beginCreateFirstUser": {
          "type": "string"
        },
        "changePassword": {
          "type": "string"
        },
        "confirmGeneration": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        },
        "emailNotValid": {
          "type": "string"
        },
        "emailSent": {
          "type": "string"
        },
        "enableAPIKey": {
          "type": "string"
        },
        "failedToUnlock": {
          "type": "string"
        },
        "forceUnlock": {
          "type": "string"
        },
        "forgotPassword": {
          "type": "string"
        },
        "forgotPasswordEmailInstructions": {
          "type": "string"
        },
        "forgotPasswordQuestion": {
          "type": "string"
        },
        "generate": {
          "type": "string"
        },
        "generateNewAPIKey": {
          "type": "string"
        },
        "logBackIn": {
          "type": "string"
        },
        "loggedOutInactivity": {
          "type": "string"
        },
        "login": {
          "type": "string"
        },
        "logOut": {
          "type": "string"
        },
        "logout": {
          "type": "string"
        },
        "logoutUser": {
          "type": "string"
        },
        "newAPIKeyGenerated": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        },
        "resetPassword": {
          "type": "string"
        },
        "stayLoggedIn": {
          "type": "string"
        },
        "successfullyUnlocked": {
          "type": "string"
        },
        "unableToVerify": {
          "type": "string"
        },
        "verified": {
          "type": "string"
        },
        "verifiedSuccessfully": {
          "type": "string"
        },
        "verify": {
          "type": "string"
        },
        "verifyUser": {
          "type": "string"
        },
        "youAreInactive": {
          "type": "string"
        }
      },
      "required": [
        "account",
        "accountOfCurrentUser",
        "alreadyActivated",
        "alreadyLoggedIn",
        "backToLogin",
        "beginCreateFirstUser",
        "changePassword",
        "confirmGeneration",
        "confirmPassword",
        "emailNotValid",
        "emailSent",
        "enableAPIKey",
        "failedToUnlock",
        "forceUnlock",
        "forgotPassword",
        "forgotPasswordEmailInstructions",
        "forgotPasswordQuestion",
        "generate",
        "generateNewAPIKey",
        "logBackIn",
        "loggedOutInactivity",
        "login",
        "logOut",
        "logout",
        "logoutUser",
        "newAPIKeyGenerated",
        "newPassword",
        "resetPassword",
        "stayLoggedIn",
        "successfullyUnlocked",
        "unableToVerify",
        "verified",
        "verifiedSuccessfully",
        "verify",
        "verifyUser",
        "youAreInactive"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "autosaving": {
          "type": "string"
        },
        "correctInvalidFields": {
          "type": "string"
        },
        "deletingTitle": {
          "type": "string"
        },
        "loadingDocument": {
          "type": "string"
        },
        "noMatchedField": {
          "type": "string"
        },
        "notAllowedToAccessPage": {
          "type": "string"
        },
        "previewing": {
          "type": "string"
        },
        "unknown": {
          "type": "string"
        }
      },
      "required": [
        "autosaving",
        "correctInvalidFields",
        "deletingTitle",
        "loadingDocument",
        "noMatchedField",
        "notAllowedToAccessPage",
        "previewing",
        "unknown"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "addLabel",
        "addNew",
        "addNewLabel",
        "block",
        "blocks",
        "blockType",
        "chooseFromExisting",
        "collapseAll",
        "itemsAndMore",
        "latitude",
        "longitude",
        "passwordsDoNotMatch",
        "searchForBlock",
        "selectFieldsToEdit",
        "showAll",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "addBelow": {
          "type": "string"
        },
        "addFilter": {
          "type": "string"
        },
        "adminTheme": {
          "type": "string"
        },
        "and": {
          "type": "string"
        },
        "applyChanges": {
          "type": "string"
        },
        "ascending": {
          "type": "string"
        },
        "automatic": {
          "type": "string"
        },
        "backToDashboard": {
          "type": "string"
        },
        "cancel": {
          "type": "string"
        },
        "changesNotSaved": {
          "type": "string"
        },
        "close": {
          "type": "string"
        },
        "collapse": {
          "type": "string"
        },
        "collections": {
          "type": "string"
        },
        "columns": {
          "type": "string"
        },
        "columnToSort": {
          "type": "string"
        },
        "confirm": {
          "type": "string"
        },
        "confirmDeletion": {
          "type": "string"
        },
        "confirmDuplication": {
          "type": "string"
        },
        "copied": {
          "type": "string"
        },
        "copy": {
          "type": "string"
        },
        "create": {
          "type": "string"
        },
        "created": {
          "type": "string"
        },
        "createNew": {
          "type": "string"
        },
        "createNewLabel": {
          "type": "string"
        },
        "creating": {
          "type": "string"
        },
        "creatingNewLabel": {
          "type": "string"
        },
        "dark": {
          "type": "string"
        },
        "dashboard": {
          "type": "string"
        },
        "delete": {
          "type": "string"
        },
        "deleting": {
          "type": "string"
        },
        "descending": {
          "type": "string"
        },
        "deselectAllRows": {
          "type": "string"
        },
        "duplicate": {
          "type": "string"
        },
        "duplicateWithoutSaving": {
          "type": "string"
        },
        "edit": {
          "type": "string"
        },
        "editing": {
          "type": "string"
        },
        "editLabel": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "emailAddress": {
          "type": "string"
        },
        "enterAValue": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "errors": {
          "type": "string"
        },
        "fallbackToDefaultLocale": {
          "type": "string"
        },
        "filters": {
          "type": "string"
        },
        "filterWhere": {
          "type": "string"
        },
        "globals": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "lastModified": {
          "type": "string"
        },
        "leaveAnyway": {
          "type": "string"
        },
        "leaveWithoutSaving": {
          "type": "string"
        },
        "light": {
          "type": "string"
        },
        "livePreview": {
          "type": "string"
        },
        "loading": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "menu": {
          "type": "string"
        },
        "moveDown": {
          "type": "string"
        },
        "moveUp": {
          "type": "string"
        },
        "noFiltersSet": {
          "type": "string"
        },
        "noLabel": {
          "type": "string"
        },
        "none": {
          "type": "string"
        },
        "noOptions": {
          "type": "string"
        },
        "noResults": {
          "type": "string"
        },
        "nothingFound": {
          "type": "string"
        },
        "noValue": {
          "type": "string"
        },
        "of": {
          "type": "string"
        },
        "open": {
          "type": "string"
        },
        "or": {
          "type": "string"
        },
        "order": {
          "type": "string"
        },
        "pageNotFound": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "payloadSettings": {
          "type": "string"
        },
        "perPage": {
          "type": "string"
        },
        "remove": {
          "type": "string"
        },
        "reset": {
          "type": "string"
        },
        "save": {
          "type": "string"
        },
        "searchBy": {
          "type": "string"
        },
        "selectAll": {
          "type": "string"
        },
        "selectAllRows": {
          "type": "string"
        },
        "selectedCount": {
          "type": "string"
        },
        "selectValue": {
          "type": "string"
        },
        "showAllLabel": {
          "type": "string"
        },
        "sorryNotFound": {
          "type": "string"
        },
        "sort": {
          "type": "string"
        },
        "sortByLabelDirection": {
          "type": "string"
        },
        "stayOnThisPage": {
          "type": "string"
        },
        "submissionSuccessful": {
          "type": "string"
        },
        "submit": {
          "type": "string"
        },
        "successfullyDuplicated": {
          "type": "string"
        },
        "titleDeleted": {
          "type": "string"
        },
        "untitled": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "updating": {
          "type": "string"
        },
        "welcome": {
          "type": "string"
        }
      },
      "required": [
        "addBelow",
        "addFilter",
        "adminTheme",
        "and",
        "ascending",
        "automatic",
        "backToDashboard",
        "cancel",
        "changesNotSaved",
        "close",
        "collections",
        "columns",
        "columnToSort",
        "confirm",
        "confirmDeletion",
        "confirmDuplication",
        "copied",
        "copy",
        "create",
        "created",
        "createNew",
        "createNewLabel",
        "creating",
        "creatingNewLabel",
        "dark",
        "dashboard",
        "delete",
        "deleting",
        "descending",
        "duplicate",
        "duplicateWithoutSaving",
        "edit",
        "editing",
        "editLabel",
        "email",
        "emailAddress",
        "enterAValue",
        "error",
        "errors",
        "fallbackToDefaultLocale",
        "filters",
        "filterWhere",
        "globals",
        "language",
        "lastModified",
        "leaveAnyway",
        "leaveWithoutSaving",
        "light",
        "loading",
        "moveDown",
        "moveUp",
        "noFiltersSet",
        "noLabel",
        "none",
        "noResults",
        "nothingFound",
        "noValue",
        "of",
        "or",
        "order",
        "pageNotFound",
        "password",
        "payloadSettings",
        "perPage",
        "remove",
        "save",
        "searchBy",
        "selectAll",
        "selectedCount",
        "selectValue",
        "sorryNotFound",
        "sort",
        "stayOnThisPage",
        "submissionSuccessful",
        "submit",
        "successfullyDuplicated",
        "titleDeleted",
        "untitled",
        "updatedAt",
        "updating",
        "welcome"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "crop": {
          "type": "string"
        },
        "cropToolDescription": {
          "type": "string"
        },
        "dragAndDrop": {
          "type": "string"
        },
        "editImage": {
          "type": "string"
        },
        "focalPoint": {
          "type": "string"
        },
        "focalPointDescription": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "previewSizes": {
          "type": "string"
        },
        "selectCollectionToBrowse": {
          "type": "string"
        },
        "selectFile": {
          "type": "string"
        },
        "setCropArea": {
          "type": "string"
        },
        "setFocalPoint": {
          "type": "string"
        },
        "sizesFor": {
          "type": "string"
        },
        "width": {
          "type": "string"
        }
      },
      "required": [
        "dragAndDrop",
        "height",
        "selectCollectionToBrowse",
        "selectFile",
        "width"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "fieldHasNo": {
          "type": "string"
        },
        "limitReached": {
          "type": "string"
        }
      },
      "required": [
        "fieldHasNo"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "aboutToRestore": {
          "type": "string"
        },
        "aboutToRestoreGlobal": {
          "type": "string"
        },
        "compareVersion": {
          "type": "string"
        },
        "confirmUnpublish": {
          "type": "string"
        },
        "confirmVersionRestoration": {
          "type": "string"
        },
        "noFurtherVersionsFound": {
          "type": "string"
        },
        "noRowsFound": {
          "type": "string"
        },
        "preview": {
          "type": "string"
        },
        "problemRestoringVersion": {
          "type": "string"
        },
        "publishChanges": {
          "type": "string"
        },
        "restoreThisVersion": {
          "type": "string"
        },
        "restoring": {
          "type": "string"
        },
        "selectLocales": {
          "type": "string"
        },
        "selectVersionToCompare": {
          "type": "string"
        },
        "showLocales": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "unpublish": {
          "type": "string"
        },
        "unpublishing": {
          "type": "string"
        },
        "versionCreatedOn": {
          "type": "string"
        },
        "versionID": {
          "type": "string"
        },
        "versions": {
          "type": "string"
        },
        "viewingVersion": {
          "type": "string"
        },
        "viewingVersionGlobal": {
          "type": "string"
        },
        "viewingVersions": {
          "type": "string"
        },
        "viewingVersionsGlobal": {
          "type": "string"
        }
      },
      "required": [
        "aboutToRestore",
        "aboutToRestoreGlobal",
        "compareVersion",
        "confirmUnpublish",
        "confirmVersionRestoration",
        "noFurtherVersionsFound",
        "noRowsFound",
        "preview",
        "problemRestoringVersion",
        "publishChanges",
        "restoreThisVersion",
        "restoring",
        "selectLocales",
        "selectVersionToCompare",
        "showLocales",
        "type",
        "unpublish",
        "unpublishing",
        "versionCreatedOn",
        "versionID",
        "versions",
        "viewingVersion",
        "viewingVersionGlobal",
        "viewingVersions",
        "viewingVersionsGlobal"
      ],
      "type": "object"
    }
  },
  "required": [
    "authentication",
    "error",
    "fields",
    "general",
    "upload",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/next/src/translations/cs.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "account": "Účet",
    "accountOfCurrentUser": "Účet současného uživatele",
    "alreadyActivated": "Již aktivováno",
    "alreadyLoggedIn": "Již přihlášen",
    "backToLogin": "Zpět na přihlášení",
    "beginCreateFirstUser": "Začněte vytvořením svého prvního uživatele.",
    "changePassword": "Změnit heslo",
    "confirmGeneration": "Potvrdit generaci",
    "confirmPassword": "Potvrdit heslo",
    "emailNotValid": "Zadaný email není platný",
    "emailSent": "Email odeslán",
    "enableAPIKey": "Povolit klíč API",
    "failedToUnlock": "Nepodařilo se odemknout",
    "forceUnlock": "Vynutit odemčení",
    "forgotPassword": "Zapomněli jste heslo?",
    "forgotPasswordEmailInstructions": "Zadejte svůj email níže. Obdržíte email s instrukcemi, jak resetovat vaše heslo.",
    "forgotPasswordQuestion": "Zapomněli jste heslo?",
    "generate": "Generovat",
    "generateNewAPIKey": "Generovat nový klíč API",
    "logBackIn": "Znovu se přihlásit",
    "logOut": "Odhlásit se",
    "loggedOutInactivity": "Byli jste odhlášeni z důvodu neaktivity.",
    "login": "Přihlásit se",
    "logout": "Odhlásit se",
    "logoutUser": "Odhlásit uživatele",
    "newAPIKeyGenerated": "Byl vygenerován nový klíč API.",
    "newPassword": "Nové heslo",
    "resetPassword": "Resetovat heslo",
    "stayLoggedIn": "Zůstat přihlášen",
    "successfullyUnlocked": "Úspěšně odemčeno",
    "unableToVerify": "Nepodařilo se ověřit",
    "verified": "Ověřeno",
    "verifiedSuccessfully": "Úspěšně ověřeno",
    "verify": "Ověřit",
    "verifyUser": "Ověřit uživatele",
    "youAreInactive": "Nějakou dobu jste nebyli aktivní a brzy budete automaticky odhlášeni z bezpečnostních důvodů. Chcete zůstat přihlášen?"
  },
  "error": {
    "autosaving": "Při automatickém ukládání tohoto dokumentu došlo k chybě.",
    "correctInvalidFields": "Opravte neplatná pole.",
    "deletingTitle": "Při mazání {{title}} došlo k chybě. Zkontrolujte své připojení a zkuste to znovu.",
    "loadingDocument": "Při načítání dokumentu s ID {{id}} došlo k chybě.",
    "noMatchedField": "Pro \"{{label}}\" nebylo nalezeno žádné odpovídající pole",
    "notAllowedToAccessPage": "Nemáte povolení přistupovat k této stránce.",
    "previewing": "Při náhledu tohoto dokumentu došlo k chybě.",
    "unknown": "Došlo k neznámé chybě."
  },
  "fields": {
    "addLabel": "Přidat {{label}}",
    "addNew": "Přidat nový",
    "addNewLabel": "Přidat nový {{label}}",
    "block": "blok",
    "blockType": "Typ bloku",
    "blocks": "bloky",
    "chooseFromExisting": "Vybrat z existujících",
    "collapseAll": "Sbalit vše",
    "itemsAndMore": "{{items}} a {{count}} dalších",
    "latitude": "Zeměpisná šířka",
    "longitude": "Zeměpisná délka",
    "passwordsDoNotMatch": "Hesla se neshodují.",
    "searchForBlock": "Hledat blok",
    "selectFieldsToEdit": "Vyberte pole, která chcete upravit",
    "showAll": "Zobrazit vše",
    "uploadNewLabel": "Nahrát nový {{label}}"
  },
  "general": {
    "addBelow": "Přidat pod",
    "addFilter": "Přidat filtr",
    "adminTheme": "Motiv administračního rozhraní",
    "and": "A",
    "applyChanges": "Použít změny",
    "ascending": "Vzestupně",
    "automatic": "Automatické",
    "backToDashboard": "Zpět na nástěnku",
    "cancel": "Zrušit",
    "changesNotSaved": "Vaše změny nebyly uloženy. Pokud teď odejdete, ztratíte své změny.",
    "close": "Zavřít",
    "collapse": "Sbalit",
    "collections": "Kolekce",
    "columnToSort": "Sloupec k seřazení",
    "columns": "Sloupce",
    "confirm": "Potvrdit",
    "confirmDeletion": "Potvrdit odstranění",
    "confirmDuplication": "Potvrdit duplikaci",
    "copied": "Zkopírováno",
    "copy": "Kopírovat",
    "create": "Vytvořit",
    "createNew": "Vytvořit nové",
    "createNewLabel": "Vytvořit nový {{label}}",
    "created": "Vytvořeno",
    "creating": "Vytváření",
    "creatingNewLabel": "Vytváření nového {{label}}",
    "dark": "Tmavé",
    "dashboard": "Nástěnka",
    "delete": "Odstranit",
    "deleting": "Odstraňování...",
    "descending": "Sestupně",
    "deselectAllRows": "Zrušte výběr všech řádků",
    "duplicate": "Duplikovat",
    "duplicateWithoutSaving": "Duplikovat bez uložení změn",
    "edit": "Upravit",
    "editLabel": "Upravit {{label}}",
    "editing": "Úpravy",
    "email": "E-mail",
    "emailAddress": "E-mailová adresa",
    "enterAValue": "Zadejte hodnotu",
    "error": "Chyba",
    "errors": "Chyby",
    "fallbackToDefaultLocale": "Zpětné přepnutí do výchozího locale",
    "filterWhere": "Filtrovat {{label}} kde",
    "filters": "Filtry",
    "globals": "Globální",
    "language": "Jazyk",
    "lastModified": "Naposledy změněno",
    "leaveAnyway": "Přesto odejít",
    "leaveWithoutSaving": "Odejít bez uložení",
    "light": "Světlé",
    "livePreview": "Náhled",
    "loading": "Načítání",
    "locale": "Místní verze",
    "menu": "Jídelní lístek",
    "moveDown": "Posunout dolů",
    "moveUp": "Posunout nahoru",
    "noFiltersSet": "Nenastaveny žádné filtry",
    "noLabel": "<Žádný {{label}}>",
    "noOptions": "Žádné možnosti",
    "noResults": "Nebyly nalezeny žádné {{label}}. Buď ještě neexistují žádné {{label}}, nebo žádné nesplňují filtry, které jste zadali výše.",
    "noValue": "Žádná hodnota",
    "none": "Žádné",
    "nothingFound": "Nic nenalezeno",
    "of": "z",
    "open": "Otevřít",
    "or": "Nebo",
    "order": "Pořadí",
    "pageNotFound": "Stránka nenalezena",
    "password": "Heslo",
    "payloadSettings": "Nastavení datového záběru",
    "perPage": "Na stránku: {{limit}}",
    "remove": "Odstranit",
    "reset": "Resetovat",
    "save": "Uložit",
    "searchBy": "Vyhledat podle {{label}}",
    "selectAll": "Vybrat vše {{count}} {{label}}",
    "selectAllRows": "Vyberte všechny řádky",
    "selectValue": "Vyberte hodnotu",
    "selectedCount": "Vybráno {{count}} {{label}}",
    "showAllLabel": "Zobrazit všechny {{label}}",
    "sorryNotFound": "Je nám líto, ale neexistuje nic, co by odpovídalo vašemu požadavku.",
    "sort": "Třídit",
    "sortByLabelDirection": "Seřadit podle {{label}} {{direction}}",
    "stayOnThisPage": "Zůstat na této stránce",
    "submissionSuccessful": "Odeslání úspěšné.",
    "submit": "Odeslat",
    "successfullyDuplicated": "{{label}} úspěšně duplikováno.",
    "titleDeleted": "{{label}} \"{{title}}\" úspěšně smazáno.",
    "untitled": "Bez názvu",
    "updatedAt": "Aktualizováno v",
    "updating": "Aktualizace",
    "welcome": "Vítejte"
  },
  "upload": {
    "crop": "Plodina",
    "cropToolDescription": "Přetáhněte rohy vybrané oblasti, nakreslete novou oblast nebo upravte hodnoty níže.",
    "dragAndDrop": "Přetáhněte soubor",
    "editImage": "Upravit obrázek",
    "focalPoint": "Středobod",
    "focalPointDescription": "Přetáhněte bod zaměření přímo na náhled nebo upravte hodnoty níže.",
    "height": "Výška",
    "previewSizes": "Náhled velikostí",
    "selectCollectionToBrowse": "Vyberte kolekci pro procházení",
    "selectFile": "Vyberte soubor",
    "setCropArea": "Nastavit oblast ořezu",
    "setFocalPoint": "Nastavit ohnisko",
    "sizesFor": "Velikosti pro {{label}}",
    "width": "Šířka"
  },
  "validation": {
    "fieldHasNo": "Toto pole nemá {{label}}",
    "limitReached": "Dosáhnutý limit, mohou být přidány pouze {{max}} položky."
  },
  "version": {
    "aboutToRestore": "Chystáte se obnovit tento {{label}} dokument do stavu, v jakém byl {{versionDate}}.",
    "aboutToRestoreGlobal": "Chystáte se obnovit globální {{label}} do stavu, v jakém byl {{versionDate}}.",
    "compareVersion": "Porovnat verzi s:",
    "confirmUnpublish": "Potvrdit zrušení publikování",
    "confirmVersionRestoration": "Potvrdit obnovení verze",
    "noFurtherVersionsFound": "Nenalezeny další verze",
    "noRowsFound": "Nenalezen {{label}}",
    "preview": "Náhled",
    "problemRestoringVersion": "Při obnovování této verze došlo k problému",
    "publishChanges": "Publikovat změny",
    "restoreThisVersion": "Obnovit tuto verzi",
    "restoring": "Obnovování...",
    "selectLocales": "Vyberte místní verze pro zobrazení",
    "selectVersionToCompare": "Vyberte verzi pro porovnání",
    "showLocales": "Zobrazit místní verze:",
    "type": "Typ",
    "unpublish": "Zrušit publikování",
    "unpublishing": "Zrušuji publikování...",
    "versionCreatedOn": "{{version}} vytvořena:",
    "versionID": "ID verze",
    "versions": "Verze",
    "viewingVersion": "Zobrazuji verzi pro {{entityLabel}} {{documentTitle}}",
    "viewingVersionGlobal": "Zobrazuji verzi pro globální {{entityLabel}}",
    "viewingVersions": "Zobrazuji verze pro {{entityLabel}} {{documentTitle}}",
    "viewingVersionsGlobal": "Zobrazuji verze pro globální {{entityLabel}}"
  }
}
