=== Myturnkeylife/Payload-tm/packages/translations/dist/api/translation-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "authentication": {
      "additionalProperties": false,
      "properties": {
        "apiKey": {
          "type": "string"
        },
        "enableAPIKey": {
          "type": "string"
        },
        "newAccountCreated": {
          "type": "string"
        },
        "resetYourPassword": {
          "type": "string"
        },
        "verifyYourEmail": {
          "type": "string"
        },
        "youAreReceivingResetPassword": {
          "type": "string"
        },
        "youDidNotRequestPassword": {
          "type": "string"
        },
        "verified": {
          "type": "string"
        }
      },
      "required": [
        "apiKey",
        "enableAPIKey",
        "newAccountCreated",
        "resetYourPassword",
        "verifyYourEmail",
        "youAreReceivingResetPassword",
        "youDidNotRequestPassword",
        "verified"
      ],
      "type": "object"
    },
    "error": {
      "additionalProperties": false,
      "properties": {
        "deletingFile": {
          "type": "string"
        },
        "emailOrPasswordIncorrect": {
          "type": "string"
        },
        "followingFieldsInvalid_one": {
          "type": "string"
        },
        "followingFieldsInvalid_other": {
          "type": "string"
        },
        "noFilesUploaded": {
          "type": "string"
        },
        "notAllowedToPerformAction": {
          "type": "string"
        },
        "problemUploadingFile": {
          "type": "string"
        },
        "unableToDeleteCount": {
          "type": "string"
        },
        "unableToUpdateCount": {
          "type": "string"
        },
        "unauthorized": {
          "type": "string"
        },
        "userLocked": {
          "type": "string"
        },
        "valueMustBeUnique": {
          "type": "string"
        }
      },
      "required": [
        "deletingFile",
        "emailOrPasswordIncorrect",
        "followingFieldsInvalid_one",
        "followingFieldsInvalid_other",
        "noFilesUploaded",
        "notAllowedToPerformAction",
        "problemUploadingFile",
        "unableToDeleteCount",
        "unableToUpdateCount",
        "unauthorized",
        "userLocked",
        "valueMustBeUnique"
      ],
      "type": "object"
    },
    "fields": {
      "additionalProperties": false,
      "properties": {
        "addLabel": {
          "type": "string"
        },
        "addLink": {
          "type": "string"
        },
        "addNew": {
          "type": "string"
        },
        "addNewLabel": {
          "type": "string"
        },
        "addRelationship": {
          "type": "string"
        },
        "addUpload": {
          "type": "string"
        },
        "block": {
          "type": "string"
        },
        "blockType": {
          "type": "string"
        },
        "blocks": {
          "type": "string"
        },
        "chooseBetweenCustomTextOrDocument": {
          "type": "string"
        },
        "chooseDocumentToLink": {
          "type": "string"
        },
        "chooseFromExisting": {
          "type": "string"
        },
        "chooseLabel": {
          "type": "string"
        },
        "collapseAll": {
          "type": "string"
        },
        "customURL": {
          "type": "string"
        },
        "editLabelData": {
          "type": "string"
        },
        "editLink": {
          "type": "string"
        },
        "editRelationship": {
          "type": "string"
        },
        "enterURL": {
          "type": "string"
        },
        "internalLink": {
          "type": "string"
        },
        "itemsAndMore": {
          "type": "string"
        },
        "labelRelationship": {
          "type": "string"
        },
        "latitude": {
          "type": "string"
        },
        "linkType": {
          "type": "string"
        },
        "linkedTo": {
          "type": "string"
        },
        "longitude": {
          "type": "string"
        },
        "newLabel": {
          "type": "string"
        },
        "openInNewTab": {
          "type": "string"
        },
        "passwordsDoNotMatch": {
          "type": "string"
        },
        "relatedDocument": {
          "type": "string"
        },
        "relationTo": {
          "type": "string"
        },
        "removeRelationship": {
          "type": "string"
        },
        "removeUpload": {
          "type": "string"
        },
        "saveChanges": {
          "type": "string"
        },
        "searchForBlock": {
          "type": "string"
        },
        "selectExistingLabel": {
          "type": "string"
        },
        "selectFieldsToEdit": {
          "type": "string"
        },
        "showAll": {
          "type": "string"
        },
        "swapRelationship": {
          "type": "string"
        },
        "swapUpload": {
          "type": "string"
        },
        "textToDisplay": {
          "type": "string"
        },
        "toggleBlock": {
          "type": "string"
        },
        "uploadNewLabel": {
          "type": "string"
        }
      },
      "required": [
        "block",
        "blocks",
        "chooseBetweenCustomTextOrDocument",
        "chooseDocumentToLink",
        "customURL",
        "editLink",
        "editRelationship",
        "enterURL",
        "internalLink",
        "linkType",
        "openInNewTab",
        "textToDisplay",
        "addLabel",
        "addLink",
        "addNew",
        "addNewLabel",
        "addRelationship",
        "addUpload",
        "blockType",
        "chooseFromExisting",
        "chooseLabel",
        "collapseAll",
        "editLabelData",
        "itemsAndMore",
        "labelRelationship",
        "latitude",
        "linkedTo",
        "longitude",
        "newLabel",
        "passwordsDoNotMatch",
        "relatedDocument",
        "relationTo",
        "removeRelationship",
        "removeUpload",
        "saveChanges",
        "searchForBlock",
        "selectExistingLabel",
        "selectFieldsToEdit",
        "showAll",
        "swapRelationship",
        "swapUpload",
        "toggleBlock",
        "uploadNewLabel"
      ],
      "type": "object"
    },
    "general": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "deletedCountSuccessfully": {
          "type": "string"
        },
        "deletedSuccessfully": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "notFound": {
          "type": "string"
        },
        "successfullyCreated": {
          "type": "string"
        },
        "thisLanguage": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "users": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedCountSuccessfully": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "createdAt",
        "deletedCountSuccessfully",
        "deletedSuccessfully",
        "email",
        "notFound",
        "successfullyCreated",
        "thisLanguage",
        "user",
        "users",
        "updatedAt",
        "updatedCountSuccessfully",
        "value"
      ],
      "type": "object"
    },
    "operators": {
      "additionalProperties": false,
      "properties": {
        "contains": {
          "type": "string"
        },
        "equals": {
          "type": "string"
        },
        "exists": {
          "type": "string"
        },
        "isGreaterThan": {
          "type": "string"
        },
        "isGreaterThanOrEqualTo": {
          "type": "string"
        },
        "isIn": {
          "type": "string"
        },
        "isLessThan": {
          "type": "string"
        },
        "isLessThanOrEqualTo": {
          "type": "string"
        },
        "isLike": {
          "type": "string"
        },
        "isNotEqualTo": {
          "type": "string"
        },
        "isNotIn": {
          "type": "string"
        },
        "near": {
          "type": "string"
        }
      },
      "required": [
        "equals",
        "isNotEqualTo",
        "isIn",
        "isNotIn",
        "exists",
        "isGreaterThan",
        "isLessThan",
        "isLessThanOrEqualTo",
        "isGreaterThanOrEqualTo",
        "near",
        "isLike",
        "contains"
      ],
      "type": "object"
    },
    "upload": {
      "additionalProperties": false,
      "properties": {
        "width": {
          "type": "string"
        },
        "height": {
          "type": "string"
        },
        "fileSize": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "sizes": {
          "type": "string"
        }
      },
      "required": [
        "width",
        "height",
        "fileSize",
        "fileName",
        "sizes"
      ],
      "type": "object"
    },
    "validation": {
      "additionalProperties": false,
      "properties": {
        "emailAddress": {
          "type": "string"
        },
        "enterNumber": {
          "type": "string"
        },
        "greaterThanMax": {
          "type": "string"
        },
        "invalidInput": {
          "type": "string"
        },
        "invalidSelection": {
          "type": "string"
        },
        "invalidSelections": {
          "type": "string"
        },
        "lessThanMin": {
          "type": "string"
        },
        "longerThanMin": {
          "type": "string"
        },
        "notValidDate": {
          "type": "string"
        },
        "requiresNoMoreThan": {
          "type": "string"
        },
        "requiresTwoNumbers": {
          "type": "string"
        },
        "shorterThanMax": {
          "type": "string"
        },
        "trueOrFalse": {
          "type": "string"
        },
        "validUploadID": {
          "type": "string"
        }
      },
      "required": [
        "emailAddress",
        "enterNumber",
        "greaterThanMax",
        "invalidInput",
        "invalidSelection",
        "invalidSelections",
        "lessThanMin",
        "longerThanMin",
        "notValidDate",
        "requiresNoMoreThan",
        "requiresTwoNumbers",
        "shorterThanMax",
        "trueOrFalse",
        "validUploadID"
      ],
      "type": "object"
    },
    "version": {
      "additionalProperties": false,
      "properties": {
        "autosavedSuccessfully": {
          "type": "string"
        },
        "draftSavedSuccessfully": {
          "type": "string"
        },
        "restoredSuccessfully": {
          "type": "string"
        },
        "draft": {
          "type": "string"
        },
        "published": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      },
      "required": [
        "autosavedSuccessfully",
        "draftSavedSuccessfully",
        "restoredSuccessfully",
        "draft",
        "published",
        "status"
      ],
      "type": "object"
    }
  },
  "required": [
    "authentication",
    "general",
    "error",
    "upload",
    "validation",
    "version"
  ],
  "type": "object"
}

=== Myturnkeylife/Payload-tm/packages/translations/dist/api/zh.json
{
  "$schema": "./translation-schema.json",
  "authentication": {
    "apiKey": "API密钥",
    "enableAPIKey": "启用API密钥",
    "newAccountCreated": "刚刚为您创建了一个可以访问 <a href=\"{{serverURL}}\">{{serverURL}}</a> 的新帐户 请点击以下链接或在浏览器中粘贴以下网址，以验证您的电子邮件: <a href=\"{{verificationURL}}\">{{verificationURL}}</a><br> 验证您的电子邮件后，您将能够成功登录。",
    "resetYourPassword": "重置您的密码",
    "verified": "已验证",
    "verifyYourEmail": "验证您的电子邮件",
    "youAreReceivingResetPassword": "您收到此邮件是因为您（或其他人）已请求重置您帐户的密码。请点击以下链接，或将其粘贴到您的浏览器中以完成该过程：",
    "youDidNotRequestPassword": "如果您没有要求这样做，请忽略这封邮件，您的密码将保持不变。"
  },
  "error": {
    "deletingFile": "删除文件时出现了错误。",
    "emailOrPasswordIncorrect": "提供的电子邮件或密码不正确。",
    "followingFieldsInvalid_one": "下面的字段是无效的：",
    "followingFieldsInvalid_other": "以下字段是无效的：",
    "noFilesUploaded": "没有上传文件。",
    "notAllowedToPerformAction": "您不被允许执行此操作。",
    "problemUploadingFile": "上传文件时出现了问题。",
    "unableToDeleteCount": "无法从 {{total}} {{label}} 中删除 {{count}}。",
    "unableToUpdateCount": "无法更新 {{count}} 个，共 {{total}} 个 {{label}}。",
    "unauthorized": "未经授权，您必须登录才能提出这个请求。",
    "userLocked": "该用户由于有太多次失败的登录尝试而被锁定。",
    "valueMustBeUnique": "值必须是唯一的"
  },
  "general": {
    "createdAt": "创建于",
    "deletedCountSuccessfully": "已成功删除 {{count}} {{label}}。",
    "deletedSuccessfully": "已成功删除。",
    "email": "电子邮件",
    "notFound": "未找到",
    "successfullyCreated": "成功创建{{label}}",
    "thisLanguage": "中文 (简体)",
    "updatedAt": "更新于",
    "updatedCountSuccessfully": "已成功更新 {{count}} {{label}}。",
    "user": "用户",
    "users": "用户",
    "value": "值"
  },
  "upload": {
    "fileName": "文件名",
    "fileSize": "文件大小",
    "height": "高度",
    "sizes": "尺寸",
    "width": "宽度"
  },
  "validation": {
    "emailAddress": "请输入一个有效的电子邮件地址。",
    "enterNumber": "请输入一个有效的号码。",
    "greaterThanMax": "{{value}}超过了允许的最大{{label}}，该最大值为{{max}}。",
    "invalidInput": "这个字段有一个无效的输入。",
    "invalidSelection": "这个字段有一个无效的选择。",
    "invalidSelections": "这个字段有以下无效的选择：",
    "lessThanMin": "{{value}}小于允许的最小{{label}}，该最小值为{{min}}。",
    "longerThanMin": "该值必须大于{{minLength}}字符的最小长度",
    "notValidDate": "\"{{value}}\"不是一个有效的日期。",
    "requiresNoMoreThan": "该字段要求不超过{{count}} {{label}。",
    "requiresTwoNumbers": "该字段需要两个数字。",
    "shorterThanMax": "该值必须小于{{maxLength}}字符的最大长度",
    "trueOrFalse": "该字段只能等于真或伪。",
    "validUploadID": "该字段不是有效的上传ID。"
  },
  "version": {
    "autosavedSuccessfully": "自动保存成功。",
    "draft": "草稿",
    "draftSavedSuccessfully": "草稿成功保存。",
    "published": "已发布",
    "restoredSuccessfully": "恢复成功。",
    "status": "状态"
  }
}
